<?php
/**
 * @file
 * shanti_texts_features.views_default.inc
 */

/**
 * Implements hook_views_default_views().
 */
function shanti_texts_features_views_default_views() {
  $export = array();

  $view = new view();
  $view->name = 'all_texts';
  $view->description = 'A view to search all texts';
  $view->tag = 'default';
  $view->base_table = 'node';
  $view->human_name = 'All Texts';
  $view->core = 7;
  $view->api_version = '3.0';
  $view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */

  /* Display: Master */
  $handler = $view->new_display('default', 'Master', 'default');
  $handler->display->display_options['title'] = 'All Texts';
  $handler->display->display_options['use_ajax'] = TRUE;
  $handler->display->display_options['use_more_always'] = FALSE;
  $handler->display->display_options['access']['type'] = 'perm';
  $handler->display->display_options['cache']['type'] = 'none';
  $handler->display->display_options['query']['type'] = 'views_query';
  $handler->display->display_options['exposed_form']['type'] = 'basic';
  $handler->display->display_options['exposed_form']['options']['submit_button'] = 'Search';
  $handler->display->display_options['exposed_form']['options']['expose_sort_order'] = FALSE;
  $handler->display->display_options['exposed_form']['options']['autosubmit'] = TRUE;
  $handler->display->display_options['pager']['type'] = 'pagerer';
  $handler->display->display_options['pager']['options']['items_per_page'] = '36';
  $handler->display->display_options['pager']['options']['offset'] = '0';
  $handler->display->display_options['pager']['options']['id'] = '0';
  $handler->display->display_options['pager']['options']['quantity'] = '9';
  $handler->display->display_options['pager']['options']['expose']['items_per_page_options'] = '6, 24, 96';
  $handler->display->display_options['pager']['options']['preset'] = 'shanti_default';
  $handler->display->display_options['style_plugin'] = 'default';
  $handler->display->display_options['style_options']['row_class_special'] = FALSE;
  $handler->display->display_options['row_plugin'] = 'fields';
  $handler->display->display_options['row_options']['inline'] = array(
    'field_dc_date_orginial_year' => 'field_dc_date_orginial_year',
    'field_dc_date_publication_year' => 'field_dc_date_publication_year',
    'field_book_author' => 'field_book_author',
  );
  /* Header: Global: Result summary */
  $handler->display->display_options['header']['result']['id'] = 'result';
  $handler->display->display_options['header']['result']['table'] = 'views';
  $handler->display->display_options['header']['result']['field'] = 'result';
  $handler->display->display_options['header']['result']['content'] = '<div class="view-result-count-info">Displaying @start - @end of @total texts</div>';
  /* No results behavior: Global: Text area */
  $handler->display->display_options['empty']['area']['id'] = 'area';
  $handler->display->display_options['empty']['area']['table'] = 'views';
  $handler->display->display_options['empty']['area']['field'] = 'area';
  $handler->display->display_options['empty']['area']['empty'] = TRUE;
  $handler->display->display_options['empty']['area']['content'] = 'Sorry, no texts match your search terms. Please try again.';
  $handler->display->display_options['empty']['area']['format'] = 'full_html';
  /* Relationship: OG membership: Group Node from OG membership */
  $handler->display->display_options['relationships']['og_membership_related_node_group']['id'] = 'og_membership_related_node_group';
  $handler->display->display_options['relationships']['og_membership_related_node_group']['table'] = 'og_membership';
  $handler->display->display_options['relationships']['og_membership_related_node_group']['field'] = 'og_membership_related_node_group';
  $handler->display->display_options['relationships']['og_membership_related_node_group']['label'] = 'Collection';
  /* Relationship: OG membership: Group Node from OG membership */
  $handler->display->display_options['relationships']['og_membership_related_node_group_1']['id'] = 'og_membership_related_node_group_1';
  $handler->display->display_options['relationships']['og_membership_related_node_group_1']['table'] = 'og_membership';
  $handler->display->display_options['relationships']['og_membership_related_node_group_1']['field'] = 'og_membership_related_node_group';
  $handler->display->display_options['relationships']['og_membership_related_node_group_1']['relationship'] = 'og_membership_related_node_group';
  $handler->display->display_options['relationships']['og_membership_related_node_group_1']['label'] = 'Parent Collection';
  /* Field: Content: Featured image */
  $handler->display->display_options['fields']['field_general_featured_image']['id'] = 'field_general_featured_image';
  $handler->display->display_options['fields']['field_general_featured_image']['table'] = 'field_data_field_general_featured_image';
  $handler->display->display_options['fields']['field_general_featured_image']['field'] = 'field_general_featured_image';
  $handler->display->display_options['fields']['field_general_featured_image']['label'] = '';
  $handler->display->display_options['fields']['field_general_featured_image']['exclude'] = TRUE;
  $handler->display->display_options['fields']['field_general_featured_image']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_general_featured_image']['click_sort_column'] = 'fid';
  $handler->display->display_options['fields']['field_general_featured_image']['settings'] = array(
    'image_style' => 'card_square',
    'image_link' => 'content',
  );
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'node';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['alter']['alter_text'] = TRUE;
  $handler->display->display_options['fields']['title']['alter']['text'] = '<h3><i class="icon shanticon-texts"></i>[title]</h3>';
  $handler->display->display_options['fields']['title']['alter']['word_boundary'] = FALSE;
  $handler->display->display_options['fields']['title']['alter']['ellipsis'] = FALSE;
  $handler->display->display_options['fields']['title']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['title']['element_wrapper_class'] = 'book-view-card-title';
  /* Field: Content: Original publication year */
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['id'] = 'field_dc_date_orginial_year';
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['table'] = 'field_data_field_dc_date_orginial_year';
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['field'] = 'field_dc_date_orginial_year';
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['label'] = '';
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['exclude'] = TRUE;
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['alter']['alter_text'] = TRUE;
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['alter']['text'] = ' [[field_dc_date_orginial_year]]';
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['hide_empty'] = TRUE;
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['settings'] = array(
    'format_type' => 'long',
    'fromto' => 'both',
    'multiple_number' => '',
    'multiple_from' => '',
    'multiple_to' => '',
  );
  /* Field: Content: Publication year */
  $handler->display->display_options['fields']['field_dc_date_publication_year']['id'] = 'field_dc_date_publication_year';
  $handler->display->display_options['fields']['field_dc_date_publication_year']['table'] = 'field_data_field_dc_date_publication_year';
  $handler->display->display_options['fields']['field_dc_date_publication_year']['field'] = 'field_dc_date_publication_year';
  $handler->display->display_options['fields']['field_dc_date_publication_year']['label'] = '';
  $handler->display->display_options['fields']['field_dc_date_publication_year']['alter']['alter_text'] = TRUE;
  $handler->display->display_options['fields']['field_dc_date_publication_year']['alter']['text'] = '[field_dc_date_publication_year][field_dc_date_orginial_year]';
  $handler->display->display_options['fields']['field_dc_date_publication_year']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_dc_date_publication_year']['settings'] = array(
    'format_type' => 'long',
    'fromto' => 'both',
    'multiple_number' => '',
    'multiple_from' => '',
    'multiple_to' => '',
  );
  /* Field: Content: Author */
  $handler->display->display_options['fields']['field_book_author']['id'] = 'field_book_author';
  $handler->display->display_options['fields']['field_book_author']['table'] = 'field_data_field_book_author';
  $handler->display->display_options['fields']['field_book_author']['field'] = 'field_book_author';
  $handler->display->display_options['fields']['field_book_author']['label'] = '';
  $handler->display->display_options['fields']['field_book_author']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_book_author']['delta_offset'] = '0';
  /* Field: Content: Description */
  $handler->display->display_options['fields']['field_dc_description']['id'] = 'field_dc_description';
  $handler->display->display_options['fields']['field_dc_description']['table'] = 'field_data_field_dc_description';
  $handler->display->display_options['fields']['field_dc_description']['field'] = 'field_dc_description';
  $handler->display->display_options['fields']['field_dc_description']['label'] = '';
  $handler->display->display_options['fields']['field_dc_description']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_dc_description']['element_wrapper_class'] = 'book-view-card-desc';
  $handler->display->display_options['fields']['field_dc_description']['type'] = 'text_summary_or_trimmed';
  $handler->display->display_options['fields']['field_dc_description']['settings'] = array(
    'trim_length' => '600',
  );
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title_1']['id'] = 'title_1';
  $handler->display->display_options['fields']['title_1']['table'] = 'node';
  $handler->display->display_options['fields']['title_1']['field'] = 'title';
  $handler->display->display_options['fields']['title_1']['relationship'] = 'og_membership_related_node_group';
  $handler->display->display_options['fields']['title_1']['label'] = '';
  $handler->display->display_options['fields']['title_1']['exclude'] = TRUE;
  $handler->display->display_options['fields']['title_1']['element_label_colon'] = FALSE;
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title_2']['id'] = 'title_2';
  $handler->display->display_options['fields']['title_2']['table'] = 'node';
  $handler->display->display_options['fields']['title_2']['field'] = 'title';
  $handler->display->display_options['fields']['title_2']['relationship'] = 'og_membership_related_node_group_1';
  $handler->display->display_options['fields']['title_2']['label'] = '';
  $handler->display->display_options['fields']['title_2']['exclude'] = TRUE;
  $handler->display->display_options['fields']['title_2']['alter']['alter_text'] = TRUE;
  $handler->display->display_options['fields']['title_2']['alter']['text'] = '[title_2] > ';
  $handler->display->display_options['fields']['title_2']['element_label_colon'] = FALSE;
  /* Field: Collection */
  $handler->display->display_options['fields']['nothing']['id'] = 'nothing';
  $handler->display->display_options['fields']['nothing']['table'] = 'views';
  $handler->display->display_options['fields']['nothing']['field'] = 'nothing';
  $handler->display->display_options['fields']['nothing']['ui_name'] = 'Collection';
  $handler->display->display_options['fields']['nothing']['label'] = '';
  $handler->display->display_options['fields']['nothing']['alter']['text'] = '[title_2][title_1]';
  $handler->display->display_options['fields']['nothing']['element_class'] = 'collection';
  $handler->display->display_options['fields']['nothing']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['nothing']['element_default_classes'] = FALSE;
  /* Sort criterion: Content: Title */
  $handler->display->display_options['sorts']['title']['id'] = 'title';
  $handler->display->display_options['sorts']['title']['table'] = 'node';
  $handler->display->display_options['sorts']['title']['field'] = 'title';
  /* Filter criterion: Content: Published */
  $handler->display->display_options['filters']['status']['id'] = 'status';
  $handler->display->display_options['filters']['status']['table'] = 'node';
  $handler->display->display_options['filters']['status']['field'] = 'status';
  $handler->display->display_options['filters']['status']['value'] = 1;
  $handler->display->display_options['filters']['status']['group'] = 1;
  $handler->display->display_options['filters']['status']['expose']['operator'] = FALSE;
  /* Filter criterion: Content: Type */
  $handler->display->display_options['filters']['type']['id'] = 'type';
  $handler->display->display_options['filters']['type']['table'] = 'node';
  $handler->display->display_options['filters']['type']['field'] = 'type';
  $handler->display->display_options['filters']['type']['value'] = array(
    'book' => 'book',
  );
  $handler->display->display_options['filters']['type']['group'] = 1;
  /* Filter criterion: Book: Depth */
  $handler->display->display_options['filters']['depth']['id'] = 'depth';
  $handler->display->display_options['filters']['depth']['table'] = 'book_menu_links';
  $handler->display->display_options['filters']['depth']['field'] = 'depth';
  $handler->display->display_options['filters']['depth']['value']['value'] = '1';
  $handler->display->display_options['filters']['depth']['group'] = 1;
  /* Filter criterion: Content: Title */
  $handler->display->display_options['filters']['title']['id'] = 'title';
  $handler->display->display_options['filters']['title']['table'] = 'node';
  $handler->display->display_options['filters']['title']['field'] = 'title';
  $handler->display->display_options['filters']['title']['operator'] = 'contains';
  $handler->display->display_options['filters']['title']['group'] = 1;
  $handler->display->display_options['filters']['title']['exposed'] = TRUE;
  $handler->display->display_options['filters']['title']['expose']['operator_id'] = 'title_op';
  $handler->display->display_options['filters']['title']['expose']['label'] = 'Title';
  $handler->display->display_options['filters']['title']['expose']['operator'] = 'title_op';
  $handler->display->display_options['filters']['title']['expose']['identifier'] = 'title';
  $handler->display->display_options['filters']['title']['expose']['remember_roles'] = array(
    2 => '2',
    1 => 0,
    3 => 0,
  );
  $handler->display->display_options['filters']['title']['expose']['autocomplete_items'] = '20';
  $handler->display->display_options['filters']['title']['expose']['autocomplete_min_chars'] = '0';
  $handler->display->display_options['filters']['title']['expose']['autocomplete_field'] = 'title';
  $handler->display->display_options['filters']['title']['expose']['autocomplete_raw_suggestion'] = 1;
  $handler->display->display_options['filters']['title']['expose']['autocomplete_raw_dropdown'] = 1;
  $handler->display->display_options['filters']['title']['expose']['autocomplete_dependent'] = 0;
  /* Filter criterion: Content: Author (field_book_author) */
  $handler->display->display_options['filters']['field_book_author_value']['id'] = 'field_book_author_value';
  $handler->display->display_options['filters']['field_book_author_value']['table'] = 'field_data_field_book_author';
  $handler->display->display_options['filters']['field_book_author_value']['field'] = 'field_book_author_value';
  $handler->display->display_options['filters']['field_book_author_value']['operator'] = 'contains';
  $handler->display->display_options['filters']['field_book_author_value']['group'] = 1;
  $handler->display->display_options['filters']['field_book_author_value']['exposed'] = TRUE;
  $handler->display->display_options['filters']['field_book_author_value']['expose']['operator_id'] = 'field_book_author_value_op';
  $handler->display->display_options['filters']['field_book_author_value']['expose']['label'] = 'Author';
  $handler->display->display_options['filters']['field_book_author_value']['expose']['operator'] = 'field_book_author_value_op';
  $handler->display->display_options['filters']['field_book_author_value']['expose']['identifier'] = 'field_book_author_value';
  $handler->display->display_options['filters']['field_book_author_value']['expose']['remember_roles'] = array(
    2 => '2',
    1 => 0,
    3 => 0,
  );
  $handler->display->display_options['filters']['field_book_author_value']['expose']['autocomplete_items'] = '10';
  $handler->display->display_options['filters']['field_book_author_value']['expose']['autocomplete_min_chars'] = '0';
  $handler->display->display_options['filters']['field_book_author_value']['expose']['autocomplete_field'] = 'field_book_author';
  $handler->display->display_options['filters']['field_book_author_value']['expose']['autocomplete_raw_suggestion'] = 1;
  $handler->display->display_options['filters']['field_book_author_value']['expose']['autocomplete_raw_dropdown'] = 1;
  $handler->display->display_options['filters']['field_book_author_value']['expose']['autocomplete_dependent'] = 0;

  /* Display: All */
  $handler = $view->new_display('page', 'All', 'page_3');
  $handler->display->display_options['path'] = 'alltexts';

  /* Display: By Subject */
  $handler = $view->new_display('page', 'By Subject', 'page_1');
  $handler->display->display_options['display_description'] = 'All Texts by Subject KMap ID';
  $handler->display->display_options['defaults']['arguments'] = FALSE;
  $handler->display->display_options['path'] = 'alltexts/subjects/%';

  /* Display: By Place */
  $handler = $view->new_display('page', 'By Place', 'page_2');
  $handler->display->display_options['display_description'] = 'All Texts by Place KMap ID';
  $handler->display->display_options['defaults']['arguments'] = FALSE;
  /* Contextual filter: Content: Places (field_kmap_places:id) */
  $handler->display->display_options['arguments']['field_kmap_places_id']['id'] = 'field_kmap_places_id';
  $handler->display->display_options['arguments']['field_kmap_places_id']['table'] = 'field_data_field_kmap_places';
  $handler->display->display_options['arguments']['field_kmap_places_id']['field'] = 'field_kmap_places_id';
  $handler->display->display_options['arguments']['field_kmap_places_id']['default_argument_type'] = 'php';
  $handler->display->display_options['arguments']['field_kmap_places_id']['summary']['number_of_records'] = '0';
  $handler->display->display_options['arguments']['field_kmap_places_id']['summary']['format'] = 'default_summary';
  $handler->display->display_options['arguments']['field_kmap_places_id']['summary_options']['items_per_page'] = '25';
  $handler->display->display_options['arguments']['field_kmap_places_id']['specify_validation'] = TRUE;
  $handler->display->display_options['arguments']['field_kmap_places_id']['validate']['type'] = 'php';
  $handler->display->display_options['arguments']['field_kmap_places_id']['validate_options']['code'] = '$parents = shanti_kmaps_fields_get_my_parents(\'field_kmap_places\',$argument);
$new_arg = $argument .\'+\'. implode(\'+\',$parents);
$new_arg = preg_replace("/(subjects|places)-/","",$new_arg);
$handler->argument = $new_arg;
return 1;';
  $handler->display->display_options['arguments']['field_kmap_places_id']['validate']['fail'] = 'empty';
  $handler->display->display_options['arguments']['field_kmap_places_id']['break_phrase'] = TRUE;
  $handler->display->display_options['path'] = 'alltexts/places/%';

  /* Display: By Collection */
  $handler = $view->new_display('page', 'By Collection', 'page_by_collection');
  $handler->display->display_options['defaults']['arguments'] = FALSE;
  /* Contextual filter: Content: Collection (field_og_collection_ref) */
  $handler->display->display_options['arguments']['field_og_collection_ref_target_id']['id'] = 'field_og_collection_ref_target_id';
  $handler->display->display_options['arguments']['field_og_collection_ref_target_id']['table'] = 'og_membership';
  $handler->display->display_options['arguments']['field_og_collection_ref_target_id']['field'] = 'field_og_collection_ref_target_id';
  $handler->display->display_options['arguments']['field_og_collection_ref_target_id']['default_action'] = 'default';
  $handler->display->display_options['arguments']['field_og_collection_ref_target_id']['default_argument_type'] = 'node';
  $handler->display->display_options['arguments']['field_og_collection_ref_target_id']['summary']['number_of_records'] = '0';
  $handler->display->display_options['arguments']['field_og_collection_ref_target_id']['summary']['format'] = 'default_summary';
  $handler->display->display_options['arguments']['field_og_collection_ref_target_id']['summary_options']['items_per_page'] = '25';
  $handler->display->display_options['arguments']['field_og_collection_ref_target_id']['break_phrase'] = TRUE;
  $handler->display->display_options['path'] = 'alltexts/collections/%';

  /* Display: My */
  $handler = $view->new_display('page', 'My', 'page_4');
  $handler->display->display_options['defaults']['arguments'] = FALSE;
  /* Contextual filter: Content: Author uid */
  $handler->display->display_options['arguments']['uid']['id'] = 'uid';
  $handler->display->display_options['arguments']['uid']['table'] = 'node';
  $handler->display->display_options['arguments']['uid']['field'] = 'uid';
  $handler->display->display_options['arguments']['uid']['default_action'] = 'default';
  $handler->display->display_options['arguments']['uid']['default_argument_type'] = 'current_user';
  $handler->display->display_options['arguments']['uid']['summary']['number_of_records'] = '0';
  $handler->display->display_options['arguments']['uid']['summary']['format'] = 'default_summary';
  $handler->display->display_options['arguments']['uid']['summary_options']['items_per_page'] = '25';
  $handler->display->display_options['path'] = 'mytexts';
  $handler->display->display_options['menu']['type'] = 'normal';
  $handler->display->display_options['menu']['title'] = 'My Texts';
  $handler->display->display_options['menu']['weight'] = '0';
  $handler->display->display_options['menu']['name'] = 'menu-test';
  $handler->display->display_options['menu']['context'] = 0;
  $handler->display->display_options['menu']['context_only_inline'] = 0;

  /* Display: Front Page */
  $handler = $view->new_display('panel_pane', 'Front Page', 'panel_pane_1');
  $handler->display->display_options['defaults']['fields'] = FALSE;
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'node';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['alter']['alter_text'] = TRUE;
  $handler->display->display_options['fields']['title']['alter']['text'] = '<h3><i class="icon shanticon-texts"></i>[title]</h3>';
  $handler->display->display_options['fields']['title']['alter']['word_boundary'] = FALSE;
  $handler->display->display_options['fields']['title']['alter']['ellipsis'] = FALSE;
  $handler->display->display_options['fields']['title']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['title']['element_wrapper_class'] = 'book-view-card-title';
  /* Field: Content: Author */
  $handler->display->display_options['fields']['field_book_author']['id'] = 'field_book_author';
  $handler->display->display_options['fields']['field_book_author']['table'] = 'field_data_field_book_author';
  $handler->display->display_options['fields']['field_book_author']['field'] = 'field_book_author';
  $handler->display->display_options['fields']['field_book_author']['label'] = '';
  $handler->display->display_options['fields']['field_book_author']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_book_author']['delta_offset'] = '0';
  /* Field: Content: Original publication year */
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['id'] = 'field_dc_date_orginial_year';
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['table'] = 'field_data_field_dc_date_orginial_year';
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['field'] = 'field_dc_date_orginial_year';
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['label'] = '';
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['exclude'] = TRUE;
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['alter']['alter_text'] = TRUE;
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['alter']['text'] = '[[field_dc_date_orginial_year]]';
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['settings'] = array(
    'format_type' => 'long',
    'fromto' => 'both',
    'multiple_number' => '',
    'multiple_from' => '',
    'multiple_to' => '',
  );
  /* Field: Content: Publication year */
  $handler->display->display_options['fields']['field_dc_date_publication_year']['id'] = 'field_dc_date_publication_year';
  $handler->display->display_options['fields']['field_dc_date_publication_year']['table'] = 'field_data_field_dc_date_publication_year';
  $handler->display->display_options['fields']['field_dc_date_publication_year']['field'] = 'field_dc_date_publication_year';
  $handler->display->display_options['fields']['field_dc_date_publication_year']['label'] = '';
  $handler->display->display_options['fields']['field_dc_date_publication_year']['alter']['alter_text'] = TRUE;
  $handler->display->display_options['fields']['field_dc_date_publication_year']['alter']['text'] = '[field_dc_date_publication_year] [field_dc_date_orginial_year]';
  $handler->display->display_options['fields']['field_dc_date_publication_year']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_dc_date_publication_year']['settings'] = array(
    'format_type' => 'long',
    'fromto' => 'both',
    'multiple_number' => '',
    'multiple_from' => '',
    'multiple_to' => '',
  );
  /* Field: Content: Description */
  $handler->display->display_options['fields']['field_dc_description']['id'] = 'field_dc_description';
  $handler->display->display_options['fields']['field_dc_description']['table'] = 'field_data_field_dc_description';
  $handler->display->display_options['fields']['field_dc_description']['field'] = 'field_dc_description';
  $handler->display->display_options['fields']['field_dc_description']['label'] = '';
  $handler->display->display_options['fields']['field_dc_description']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_dc_description']['element_wrapper_class'] = 'book-view-card-desc';
  $handler->display->display_options['fields']['field_dc_description']['type'] = 'text_summary_or_trimmed';
  $handler->display->display_options['fields']['field_dc_description']['settings'] = array(
    'trim_length' => '600',
  );
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title_1']['id'] = 'title_1';
  $handler->display->display_options['fields']['title_1']['table'] = 'node';
  $handler->display->display_options['fields']['title_1']['field'] = 'title';
  $handler->display->display_options['fields']['title_1']['relationship'] = 'og_membership_related_node_group';
  $handler->display->display_options['fields']['title_1']['label'] = '';
  $handler->display->display_options['fields']['title_1']['exclude'] = TRUE;
  $handler->display->display_options['fields']['title_1']['element_label_colon'] = FALSE;
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title_2']['id'] = 'title_2';
  $handler->display->display_options['fields']['title_2']['table'] = 'node';
  $handler->display->display_options['fields']['title_2']['field'] = 'title';
  $handler->display->display_options['fields']['title_2']['relationship'] = 'og_membership_related_node_group_1';
  $handler->display->display_options['fields']['title_2']['label'] = '';
  $handler->display->display_options['fields']['title_2']['exclude'] = TRUE;
  $handler->display->display_options['fields']['title_2']['alter']['alter_text'] = TRUE;
  $handler->display->display_options['fields']['title_2']['alter']['text'] = '[title_2] > ';
  $handler->display->display_options['fields']['title_2']['element_label_colon'] = FALSE;
  /* Field: Global: Custom text */
  $handler->display->display_options['fields']['nothing']['id'] = 'nothing';
  $handler->display->display_options['fields']['nothing']['table'] = 'views';
  $handler->display->display_options['fields']['nothing']['field'] = 'nothing';
  $handler->display->display_options['fields']['nothing']['label'] = '';
  $handler->display->display_options['fields']['nothing']['alter']['text'] = '[title_2][title_1]';
  $handler->display->display_options['fields']['nothing']['element_label_colon'] = FALSE;
  $handler->display->display_options['pane_description'] = 'View All Texts';
  $handler->display->display_options['allow']['use_pager'] = 'use_pager';
  $handler->display->display_options['allow']['items_per_page'] = 'items_per_page';
  $handler->display->display_options['allow']['offset'] = 0;
  $handler->display->display_options['allow']['link_to_view'] = 0;
  $handler->display->display_options['allow']['more_link'] = 0;
  $handler->display->display_options['allow']['path_override'] = 0;
  $handler->display->display_options['allow']['title_override'] = 'title_override';
  $handler->display->display_options['allow']['exposed_form'] = 0;
  $handler->display->display_options['allow']['fields_override'] = 0;
  $handler->display->display_options['argument_input'] = array(
    'nid' => array(
      'type' => 'context',
      'context' => 'entity:node.nid',
      'context_optional' => 0,
      'panel' => '0',
      'fixed' => '',
      'label' => 'Content: Nid',
    ),
  );
  $handler->display->display_options['inherit_panels_path'] = '1';

  /* Display: Pane by Collection */
  $handler = $view->new_display('panel_pane', 'Pane by Collection', 'panel_pane_2');
  $handler->display->display_options['defaults']['title'] = FALSE;
  $handler->display->display_options['title'] = 'All Texts by Collection';
  $handler->display->display_options['defaults']['relationships'] = FALSE;
  /* Relationship: OG membership: Group Node from OG membership */
  $handler->display->display_options['relationships']['og_membership_related_node_group']['id'] = 'og_membership_related_node_group';
  $handler->display->display_options['relationships']['og_membership_related_node_group']['table'] = 'og_membership';
  $handler->display->display_options['relationships']['og_membership_related_node_group']['field'] = 'og_membership_related_node_group';
  $handler->display->display_options['relationships']['og_membership_related_node_group']['required'] = TRUE;
  $handler->display->display_options['defaults']['fields'] = FALSE;
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'node';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['alter']['alter_text'] = TRUE;
  $handler->display->display_options['fields']['title']['alter']['text'] = '<h3><i class="icon shanticon-texts"></i>[title]</h3>';
  $handler->display->display_options['fields']['title']['alter']['word_boundary'] = FALSE;
  $handler->display->display_options['fields']['title']['alter']['ellipsis'] = FALSE;
  $handler->display->display_options['fields']['title']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['title']['element_wrapper_class'] = 'book-view-card-title';
  /* Field: Content: Author */
  $handler->display->display_options['fields']['field_book_author']['id'] = 'field_book_author';
  $handler->display->display_options['fields']['field_book_author']['table'] = 'field_data_field_book_author';
  $handler->display->display_options['fields']['field_book_author']['field'] = 'field_book_author';
  $handler->display->display_options['fields']['field_book_author']['label'] = '';
  $handler->display->display_options['fields']['field_book_author']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_book_author']['delta_offset'] = '0';
  /* Field: Content: Original publication year */
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['id'] = 'field_dc_date_orginial_year';
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['table'] = 'field_data_field_dc_date_orginial_year';
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['field'] = 'field_dc_date_orginial_year';
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['label'] = '';
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['exclude'] = TRUE;
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['alter']['alter_text'] = TRUE;
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['alter']['text'] = '[[field_dc_date_orginial_year]]';
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['settings'] = array(
    'format_type' => 'long',
    'fromto' => 'both',
    'multiple_number' => '',
    'multiple_from' => '',
    'multiple_to' => '',
  );
  /* Field: Content: Publication year */
  $handler->display->display_options['fields']['field_dc_date_publication_year']['id'] = 'field_dc_date_publication_year';
  $handler->display->display_options['fields']['field_dc_date_publication_year']['table'] = 'field_data_field_dc_date_publication_year';
  $handler->display->display_options['fields']['field_dc_date_publication_year']['field'] = 'field_dc_date_publication_year';
  $handler->display->display_options['fields']['field_dc_date_publication_year']['label'] = '';
  $handler->display->display_options['fields']['field_dc_date_publication_year']['alter']['alter_text'] = TRUE;
  $handler->display->display_options['fields']['field_dc_date_publication_year']['alter']['text'] = '[field_dc_date_publication_year] [field_dc_date_orginial_year]';
  $handler->display->display_options['fields']['field_dc_date_publication_year']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_dc_date_publication_year']['settings'] = array(
    'format_type' => 'long',
    'fromto' => 'both',
    'multiple_number' => '',
    'multiple_from' => '',
    'multiple_to' => '',
  );
  /* Field: Content: Description */
  $handler->display->display_options['fields']['field_dc_description']['id'] = 'field_dc_description';
  $handler->display->display_options['fields']['field_dc_description']['table'] = 'field_data_field_dc_description';
  $handler->display->display_options['fields']['field_dc_description']['field'] = 'field_dc_description';
  $handler->display->display_options['fields']['field_dc_description']['label'] = '';
  $handler->display->display_options['fields']['field_dc_description']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_dc_description']['element_wrapper_class'] = 'book-view-card-desc';
  $handler->display->display_options['fields']['field_dc_description']['type'] = 'text_summary_or_trimmed';
  $handler->display->display_options['fields']['field_dc_description']['settings'] = array(
    'trim_length' => '600',
  );
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title_1']['id'] = 'title_1';
  $handler->display->display_options['fields']['title_1']['table'] = 'node';
  $handler->display->display_options['fields']['title_1']['field'] = 'title';
  $handler->display->display_options['fields']['title_1']['relationship'] = 'og_membership_related_node_group';
  $handler->display->display_options['fields']['title_1']['label'] = '';
  $handler->display->display_options['fields']['title_1']['element_label_colon'] = FALSE;
  $handler->display->display_options['defaults']['arguments'] = FALSE;
  /* Contextual filter: Content: Collection (field_og_collection_ref) */
  $handler->display->display_options['arguments']['field_og_collection_ref_target_id']['id'] = 'field_og_collection_ref_target_id';
  $handler->display->display_options['arguments']['field_og_collection_ref_target_id']['table'] = 'og_membership';
  $handler->display->display_options['arguments']['field_og_collection_ref_target_id']['field'] = 'field_og_collection_ref_target_id';
  $handler->display->display_options['arguments']['field_og_collection_ref_target_id']['default_action'] = 'default';
  $handler->display->display_options['arguments']['field_og_collection_ref_target_id']['default_argument_type'] = 'node';
  $handler->display->display_options['arguments']['field_og_collection_ref_target_id']['summary']['number_of_records'] = '0';
  $handler->display->display_options['arguments']['field_og_collection_ref_target_id']['summary']['format'] = 'default_summary';
  $handler->display->display_options['arguments']['field_og_collection_ref_target_id']['summary_options']['items_per_page'] = '25';
  $handler->display->display_options['arguments']['field_og_collection_ref_target_id']['break_phrase'] = TRUE;
  $handler->display->display_options['pane_title'] = 'All Texts by Collection';
  $handler->display->display_options['pane_description'] = 'View All Texts by Colleciton';
  $handler->display->display_options['pane_category']['name'] = 'SHANTI';
  $handler->display->display_options['pane_category']['weight'] = '0';
  $handler->display->display_options['allow']['use_pager'] = 'use_pager';
  $handler->display->display_options['allow']['items_per_page'] = 'items_per_page';
  $handler->display->display_options['allow']['offset'] = 0;
  $handler->display->display_options['allow']['link_to_view'] = 0;
  $handler->display->display_options['allow']['more_link'] = 0;
  $handler->display->display_options['allow']['path_override'] = 0;
  $handler->display->display_options['allow']['title_override'] = 'title_override';
  $handler->display->display_options['allow']['exposed_form'] = 0;
  $handler->display->display_options['allow']['fields_override'] = 'fields_override';
  $handler->display->display_options['argument_input'] = array(
    'field_og_collection_ref_target_id' => array(
      'type' => 'context',
      'context' => 'entity:node.nid',
      'context_optional' => 0,
      'panel' => '0',
      'fixed' => '',
      'label' => 'Content: Collection (field_og_collection_ref)',
    ),
  );
  $handler->display->display_options['inherit_panels_path'] = '1';

  /* Display: Pane by Collection 2 */
  $handler = $view->new_display('panel_pane', 'Pane by Collection 2', 'panel_pane_3');
  $handler->display->display_options['defaults']['title'] = FALSE;
  $handler->display->display_options['title'] = 'All Texts by Collection';
  $handler->display->display_options['defaults']['fields'] = FALSE;
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'node';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['alter']['alter_text'] = TRUE;
  $handler->display->display_options['fields']['title']['alter']['text'] = '<h3><i class="icon shanticon-texts"></i>[title]</h3>';
  $handler->display->display_options['fields']['title']['alter']['word_boundary'] = FALSE;
  $handler->display->display_options['fields']['title']['alter']['ellipsis'] = FALSE;
  $handler->display->display_options['fields']['title']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['title']['element_wrapper_class'] = 'book-view-card-title';
  /* Field: Content: Author */
  $handler->display->display_options['fields']['field_book_author']['id'] = 'field_book_author';
  $handler->display->display_options['fields']['field_book_author']['table'] = 'field_data_field_book_author';
  $handler->display->display_options['fields']['field_book_author']['field'] = 'field_book_author';
  $handler->display->display_options['fields']['field_book_author']['label'] = '';
  $handler->display->display_options['fields']['field_book_author']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_book_author']['delta_offset'] = '0';
  /* Field: Content: Original publication year */
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['id'] = 'field_dc_date_orginial_year';
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['table'] = 'field_data_field_dc_date_orginial_year';
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['field'] = 'field_dc_date_orginial_year';
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['label'] = '';
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['exclude'] = TRUE;
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['alter']['alter_text'] = TRUE;
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['alter']['text'] = '[[field_dc_date_orginial_year]]';
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['settings'] = array(
    'format_type' => 'long',
    'fromto' => 'both',
    'multiple_number' => '',
    'multiple_from' => '',
    'multiple_to' => '',
  );
  /* Field: Content: Publication year */
  $handler->display->display_options['fields']['field_dc_date_publication_year']['id'] = 'field_dc_date_publication_year';
  $handler->display->display_options['fields']['field_dc_date_publication_year']['table'] = 'field_data_field_dc_date_publication_year';
  $handler->display->display_options['fields']['field_dc_date_publication_year']['field'] = 'field_dc_date_publication_year';
  $handler->display->display_options['fields']['field_dc_date_publication_year']['label'] = '';
  $handler->display->display_options['fields']['field_dc_date_publication_year']['alter']['alter_text'] = TRUE;
  $handler->display->display_options['fields']['field_dc_date_publication_year']['alter']['text'] = '[field_dc_date_publication_year] [field_dc_date_orginial_year]';
  $handler->display->display_options['fields']['field_dc_date_publication_year']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_dc_date_publication_year']['settings'] = array(
    'format_type' => 'long',
    'fromto' => 'both',
    'multiple_number' => '',
    'multiple_from' => '',
    'multiple_to' => '',
  );
  /* Field: Content: Description */
  $handler->display->display_options['fields']['field_dc_description']['id'] = 'field_dc_description';
  $handler->display->display_options['fields']['field_dc_description']['table'] = 'field_data_field_dc_description';
  $handler->display->display_options['fields']['field_dc_description']['field'] = 'field_dc_description';
  $handler->display->display_options['fields']['field_dc_description']['label'] = '';
  $handler->display->display_options['fields']['field_dc_description']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_dc_description']['element_wrapper_class'] = 'book-view-card-desc';
  $handler->display->display_options['fields']['field_dc_description']['type'] = 'text_summary_or_trimmed';
  $handler->display->display_options['fields']['field_dc_description']['settings'] = array(
    'trim_length' => '600',
  );
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title_1']['id'] = 'title_1';
  $handler->display->display_options['fields']['title_1']['table'] = 'node';
  $handler->display->display_options['fields']['title_1']['field'] = 'title';
  $handler->display->display_options['fields']['title_1']['relationship'] = 'og_membership_related_node_group';
  $handler->display->display_options['fields']['title_1']['label'] = '';
  $handler->display->display_options['fields']['title_1']['exclude'] = TRUE;
  $handler->display->display_options['fields']['title_1']['element_label_colon'] = FALSE;
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title_2']['id'] = 'title_2';
  $handler->display->display_options['fields']['title_2']['table'] = 'node';
  $handler->display->display_options['fields']['title_2']['field'] = 'title';
  $handler->display->display_options['fields']['title_2']['relationship'] = 'og_membership_related_node_group_1';
  $handler->display->display_options['fields']['title_2']['label'] = '';
  $handler->display->display_options['fields']['title_2']['exclude'] = TRUE;
  $handler->display->display_options['fields']['title_2']['alter']['alter_text'] = TRUE;
  $handler->display->display_options['fields']['title_2']['alter']['text'] = '[title_2] > ';
  $handler->display->display_options['fields']['title_2']['element_label_colon'] = FALSE;
  /* Field: Global: Custom text */
  $handler->display->display_options['fields']['nothing']['id'] = 'nothing';
  $handler->display->display_options['fields']['nothing']['table'] = 'views';
  $handler->display->display_options['fields']['nothing']['field'] = 'nothing';
  $handler->display->display_options['fields']['nothing']['label'] = '';
  $handler->display->display_options['fields']['nothing']['alter']['text'] = '[title_2][title_1]';
  $handler->display->display_options['fields']['nothing']['element_label_colon'] = FALSE;
  $handler->display->display_options['defaults']['arguments'] = FALSE;
  /* Contextual filter: Content: Collection (field_og_collection_ref) */
  $handler->display->display_options['arguments']['field_og_collection_ref_target_id']['id'] = 'field_og_collection_ref_target_id';
  $handler->display->display_options['arguments']['field_og_collection_ref_target_id']['table'] = 'og_membership';
  $handler->display->display_options['arguments']['field_og_collection_ref_target_id']['field'] = 'field_og_collection_ref_target_id';
  $handler->display->display_options['arguments']['field_og_collection_ref_target_id']['default_action'] = 'default';
  $handler->display->display_options['arguments']['field_og_collection_ref_target_id']['default_argument_type'] = 'node';
  $handler->display->display_options['arguments']['field_og_collection_ref_target_id']['summary']['number_of_records'] = '0';
  $handler->display->display_options['arguments']['field_og_collection_ref_target_id']['summary']['format'] = 'default_summary';
  $handler->display->display_options['arguments']['field_og_collection_ref_target_id']['summary_options']['items_per_page'] = '25';
  $handler->display->display_options['arguments']['field_og_collection_ref_target_id']['break_phrase'] = TRUE;
  $handler->display->display_options['pane_title'] = 'All Texts by Collection + Subs';
  $handler->display->display_options['pane_description'] = 'View All Texts by Colleciton';
  $handler->display->display_options['pane_category']['name'] = 'SHANTI';
  $handler->display->display_options['pane_category']['weight'] = '0';
  $handler->display->display_options['allow']['use_pager'] = 'use_pager';
  $handler->display->display_options['allow']['items_per_page'] = 'items_per_page';
  $handler->display->display_options['allow']['offset'] = 0;
  $handler->display->display_options['allow']['link_to_view'] = 0;
  $handler->display->display_options['allow']['more_link'] = 0;
  $handler->display->display_options['allow']['path_override'] = 0;
  $handler->display->display_options['allow']['title_override'] = 'title_override';
  $handler->display->display_options['allow']['exposed_form'] = 0;
  $handler->display->display_options['allow']['fields_override'] = 'fields_override';
  $handler->display->display_options['argument_input'] = array(
    'field_og_collection_ref_target_id' => array(
      'type' => 'context',
      'context' => 'entity:node.nid',
      'context_optional' => 0,
      'panel' => '0',
      'fixed' => '',
      'label' => 'Content: Collection (field_og_collection_ref)',
    ),
  );
  $handler->display->display_options['inherit_panels_path'] = '1';
  $export['all_texts'] = $view;

  $view = new view();
  $view->name = 'all_texts_open';
  $view->description = 'A view to search all texts';
  $view->tag = 'default';
  $view->base_table = 'node';
  $view->human_name = 'All Texts Open';
  $view->core = 7;
  $view->api_version = '3.0';
  $view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */

  /* Display: Master */
  $handler = $view->new_display('default', 'Master', 'default');
  $handler->display->display_options['title'] = 'All Texts';
  $handler->display->display_options['use_ajax'] = TRUE;
  $handler->display->display_options['use_more_always'] = FALSE;
  $handler->display->display_options['access']['type'] = 'perm';
  $handler->display->display_options['cache']['type'] = 'none';
  $handler->display->display_options['query']['type'] = 'views_query';
  $handler->display->display_options['exposed_form']['type'] = 'basic';
  $handler->display->display_options['exposed_form']['options']['submit_button'] = 'Search';
  $handler->display->display_options['exposed_form']['options']['expose_sort_order'] = FALSE;
  $handler->display->display_options['exposed_form']['options']['autosubmit'] = TRUE;
  $handler->display->display_options['pager']['type'] = 'pagerer';
  $handler->display->display_options['pager']['options']['items_per_page'] = '36';
  $handler->display->display_options['pager']['options']['offset'] = '0';
  $handler->display->display_options['pager']['options']['id'] = '0';
  $handler->display->display_options['pager']['options']['quantity'] = '9';
  $handler->display->display_options['pager']['options']['expose']['items_per_page_options'] = '6, 24, 96';
  $handler->display->display_options['pager']['options']['preset'] = 'shanti_default';
  $handler->display->display_options['style_plugin'] = 'default';
  $handler->display->display_options['style_options']['row_class_special'] = FALSE;
  $handler->display->display_options['row_plugin'] = 'fields';
  $handler->display->display_options['row_options']['inline'] = array(
    'field_dc_date_orginial_year' => 'field_dc_date_orginial_year',
    'field_dc_date_publication_year' => 'field_dc_date_publication_year',
    'field_book_author' => 'field_book_author',
  );
  /* Header: Global: Result summary */
  $handler->display->display_options['header']['result']['id'] = 'result';
  $handler->display->display_options['header']['result']['table'] = 'views';
  $handler->display->display_options['header']['result']['field'] = 'result';
  $handler->display->display_options['header']['result']['content'] = '<div class="view-result-count-info">Displaying @start - @end of @total texts</div>';
  /* No results behavior: Global: Text area */
  $handler->display->display_options['empty']['area']['id'] = 'area';
  $handler->display->display_options['empty']['area']['table'] = 'views';
  $handler->display->display_options['empty']['area']['field'] = 'area';
  $handler->display->display_options['empty']['area']['empty'] = TRUE;
  $handler->display->display_options['empty']['area']['content'] = 'Sorry, no texts match your search terms. Please try again.';
  $handler->display->display_options['empty']['area']['format'] = 'full_html';
  /* Field: Content: Featured image */
  $handler->display->display_options['fields']['field_general_featured_image']['id'] = 'field_general_featured_image';
  $handler->display->display_options['fields']['field_general_featured_image']['table'] = 'field_data_field_general_featured_image';
  $handler->display->display_options['fields']['field_general_featured_image']['field'] = 'field_general_featured_image';
  $handler->display->display_options['fields']['field_general_featured_image']['label'] = '';
  $handler->display->display_options['fields']['field_general_featured_image']['exclude'] = TRUE;
  $handler->display->display_options['fields']['field_general_featured_image']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_general_featured_image']['click_sort_column'] = 'fid';
  $handler->display->display_options['fields']['field_general_featured_image']['settings'] = array(
    'image_style' => 'card_square',
    'image_link' => 'content',
  );
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'node';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['alter']['alter_text'] = TRUE;
  $handler->display->display_options['fields']['title']['alter']['text'] = '<h3><i class="icon shanticon-texts"></i>[title]</h3>';
  $handler->display->display_options['fields']['title']['alter']['word_boundary'] = FALSE;
  $handler->display->display_options['fields']['title']['alter']['ellipsis'] = FALSE;
  $handler->display->display_options['fields']['title']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['title']['element_wrapper_class'] = 'book-view-card-title';
  /* Field: Content: Original publication year */
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['id'] = 'field_dc_date_orginial_year';
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['table'] = 'field_data_field_dc_date_orginial_year';
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['field'] = 'field_dc_date_orginial_year';
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['label'] = '';
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['exclude'] = TRUE;
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['alter']['alter_text'] = TRUE;
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['alter']['text'] = ' [[field_dc_date_orginial_year]]';
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['hide_empty'] = TRUE;
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['settings'] = array(
    'format_type' => 'long',
    'fromto' => 'both',
    'multiple_number' => '',
    'multiple_from' => '',
    'multiple_to' => '',
  );
  /* Field: Content: Publication year */
  $handler->display->display_options['fields']['field_dc_date_publication_year']['id'] = 'field_dc_date_publication_year';
  $handler->display->display_options['fields']['field_dc_date_publication_year']['table'] = 'field_data_field_dc_date_publication_year';
  $handler->display->display_options['fields']['field_dc_date_publication_year']['field'] = 'field_dc_date_publication_year';
  $handler->display->display_options['fields']['field_dc_date_publication_year']['label'] = '';
  $handler->display->display_options['fields']['field_dc_date_publication_year']['alter']['alter_text'] = TRUE;
  $handler->display->display_options['fields']['field_dc_date_publication_year']['alter']['text'] = '[field_dc_date_publication_year][field_dc_date_orginial_year]';
  $handler->display->display_options['fields']['field_dc_date_publication_year']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_dc_date_publication_year']['settings'] = array(
    'format_type' => 'long',
    'fromto' => 'both',
    'multiple_number' => '',
    'multiple_from' => '',
    'multiple_to' => '',
  );
  /* Field: Content: Author */
  $handler->display->display_options['fields']['field_book_author']['id'] = 'field_book_author';
  $handler->display->display_options['fields']['field_book_author']['table'] = 'field_data_field_book_author';
  $handler->display->display_options['fields']['field_book_author']['field'] = 'field_book_author';
  $handler->display->display_options['fields']['field_book_author']['label'] = '';
  $handler->display->display_options['fields']['field_book_author']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_book_author']['delta_offset'] = '0';
  /* Field: Content: Description */
  $handler->display->display_options['fields']['field_dc_description']['id'] = 'field_dc_description';
  $handler->display->display_options['fields']['field_dc_description']['table'] = 'field_data_field_dc_description';
  $handler->display->display_options['fields']['field_dc_description']['field'] = 'field_dc_description';
  $handler->display->display_options['fields']['field_dc_description']['label'] = '';
  $handler->display->display_options['fields']['field_dc_description']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_dc_description']['element_wrapper_class'] = 'book-view-card-desc';
  $handler->display->display_options['fields']['field_dc_description']['type'] = 'text_summary_or_trimmed';
  $handler->display->display_options['fields']['field_dc_description']['settings'] = array(
    'trim_length' => '600',
  );
  /* Field: Content: Collection */
  $handler->display->display_options['fields']['field_og_collection_ref']['id'] = 'field_og_collection_ref';
  $handler->display->display_options['fields']['field_og_collection_ref']['table'] = 'og_membership';
  $handler->display->display_options['fields']['field_og_collection_ref']['field'] = 'field_og_collection_ref';
  $handler->display->display_options['fields']['field_og_collection_ref']['label'] = '';
  $handler->display->display_options['fields']['field_og_collection_ref']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_og_collection_ref']['settings'] = array(
    'link' => 0,
  );
  /* Sort criterion: Content: Title */
  $handler->display->display_options['sorts']['title']['id'] = 'title';
  $handler->display->display_options['sorts']['title']['table'] = 'node';
  $handler->display->display_options['sorts']['title']['field'] = 'title';
  /* Filter criterion: Content: Published */
  $handler->display->display_options['filters']['status']['id'] = 'status';
  $handler->display->display_options['filters']['status']['table'] = 'node';
  $handler->display->display_options['filters']['status']['field'] = 'status';
  $handler->display->display_options['filters']['status']['value'] = 1;
  $handler->display->display_options['filters']['status']['group'] = 1;
  $handler->display->display_options['filters']['status']['expose']['operator'] = FALSE;
  /* Filter criterion: Content: Type */
  $handler->display->display_options['filters']['type']['id'] = 'type';
  $handler->display->display_options['filters']['type']['table'] = 'node';
  $handler->display->display_options['filters']['type']['field'] = 'type';
  $handler->display->display_options['filters']['type']['value'] = array(
    'book' => 'book',
  );
  $handler->display->display_options['filters']['type']['group'] = 1;
  /* Filter criterion: Book: Depth */
  $handler->display->display_options['filters']['depth']['id'] = 'depth';
  $handler->display->display_options['filters']['depth']['table'] = 'book_menu_links';
  $handler->display->display_options['filters']['depth']['field'] = 'depth';
  $handler->display->display_options['filters']['depth']['value']['value'] = '1';
  $handler->display->display_options['filters']['depth']['group'] = 1;
  /* Filter criterion: Content: Title */
  $handler->display->display_options['filters']['title']['id'] = 'title';
  $handler->display->display_options['filters']['title']['table'] = 'node';
  $handler->display->display_options['filters']['title']['field'] = 'title';
  $handler->display->display_options['filters']['title']['operator'] = 'contains';
  $handler->display->display_options['filters']['title']['group'] = 1;
  $handler->display->display_options['filters']['title']['exposed'] = TRUE;
  $handler->display->display_options['filters']['title']['expose']['operator_id'] = 'title_op';
  $handler->display->display_options['filters']['title']['expose']['label'] = 'Title';
  $handler->display->display_options['filters']['title']['expose']['operator'] = 'title_op';
  $handler->display->display_options['filters']['title']['expose']['identifier'] = 'title';
  $handler->display->display_options['filters']['title']['expose']['remember_roles'] = array(
    2 => '2',
    1 => 0,
    3 => 0,
  );
  $handler->display->display_options['filters']['title']['expose']['autocomplete_items'] = '20';
  $handler->display->display_options['filters']['title']['expose']['autocomplete_min_chars'] = '0';
  $handler->display->display_options['filters']['title']['expose']['autocomplete_field'] = 'title';
  $handler->display->display_options['filters']['title']['expose']['autocomplete_raw_suggestion'] = 1;
  $handler->display->display_options['filters']['title']['expose']['autocomplete_raw_dropdown'] = 1;
  $handler->display->display_options['filters']['title']['expose']['autocomplete_dependent'] = 0;
  /* Filter criterion: Content: Author (field_book_author) */
  $handler->display->display_options['filters']['field_book_author_value']['id'] = 'field_book_author_value';
  $handler->display->display_options['filters']['field_book_author_value']['table'] = 'field_data_field_book_author';
  $handler->display->display_options['filters']['field_book_author_value']['field'] = 'field_book_author_value';
  $handler->display->display_options['filters']['field_book_author_value']['operator'] = 'contains';
  $handler->display->display_options['filters']['field_book_author_value']['group'] = 1;
  $handler->display->display_options['filters']['field_book_author_value']['exposed'] = TRUE;
  $handler->display->display_options['filters']['field_book_author_value']['expose']['operator_id'] = 'field_book_author_value_op';
  $handler->display->display_options['filters']['field_book_author_value']['expose']['label'] = 'Author';
  $handler->display->display_options['filters']['field_book_author_value']['expose']['operator'] = 'field_book_author_value_op';
  $handler->display->display_options['filters']['field_book_author_value']['expose']['identifier'] = 'field_book_author_value';
  $handler->display->display_options['filters']['field_book_author_value']['expose']['remember_roles'] = array(
    2 => '2',
    1 => 0,
    3 => 0,
  );
  $handler->display->display_options['filters']['field_book_author_value']['expose']['autocomplete_items'] = '10';
  $handler->display->display_options['filters']['field_book_author_value']['expose']['autocomplete_min_chars'] = '0';
  $handler->display->display_options['filters']['field_book_author_value']['expose']['autocomplete_field'] = 'field_book_author';
  $handler->display->display_options['filters']['field_book_author_value']['expose']['autocomplete_raw_suggestion'] = 1;
  $handler->display->display_options['filters']['field_book_author_value']['expose']['autocomplete_raw_dropdown'] = 1;
  $handler->display->display_options['filters']['field_book_author_value']['expose']['autocomplete_dependent'] = 0;

  /* Display: All */
  $handler = $view->new_display('page', 'All', 'page_3');
  $handler->display->display_options['path'] = 'alltexts_open';

  /* Display: By Subject */
  $handler = $view->new_display('page', 'By Subject', 'page_1');
  $handler->display->display_options['display_description'] = 'All Texts by Subject KMap ID';
  $handler->display->display_options['defaults']['arguments'] = FALSE;
  $handler->display->display_options['path'] = 'alltexts_open/subjects/%';

  /* Display: By Place */
  $handler = $view->new_display('page', 'By Place', 'page_2');
  $handler->display->display_options['display_description'] = 'All Texts by Place KMap ID';
  $handler->display->display_options['defaults']['arguments'] = FALSE;
  /* Contextual filter: Content: Places (field_kmap_places:id) */
  $handler->display->display_options['arguments']['field_kmap_places_id']['id'] = 'field_kmap_places_id';
  $handler->display->display_options['arguments']['field_kmap_places_id']['table'] = 'field_data_field_kmap_places';
  $handler->display->display_options['arguments']['field_kmap_places_id']['field'] = 'field_kmap_places_id';
  $handler->display->display_options['arguments']['field_kmap_places_id']['default_argument_type'] = 'php';
  $handler->display->display_options['arguments']['field_kmap_places_id']['summary']['number_of_records'] = '0';
  $handler->display->display_options['arguments']['field_kmap_places_id']['summary']['format'] = 'default_summary';
  $handler->display->display_options['arguments']['field_kmap_places_id']['summary_options']['items_per_page'] = '25';
  $handler->display->display_options['arguments']['field_kmap_places_id']['specify_validation'] = TRUE;
  $handler->display->display_options['arguments']['field_kmap_places_id']['validate']['type'] = 'php';
  $handler->display->display_options['arguments']['field_kmap_places_id']['validate_options']['code'] = '$parents = shanti_kmaps_fields_get_my_parents(\'field_kmap_places\',$argument);
$new_arg = $argument .\'+\'. implode(\'+\',$parents);
$new_arg = preg_replace("/(subjects|places)-/","",$new_arg);
$handler->argument = $new_arg;
return 1;';
  $handler->display->display_options['arguments']['field_kmap_places_id']['validate']['fail'] = 'empty';
  $handler->display->display_options['arguments']['field_kmap_places_id']['break_phrase'] = TRUE;
  $handler->display->display_options['path'] = 'alltexts_open/places/%';

  /* Display: By Collection */
  $handler = $view->new_display('page', 'By Collection', 'page_by_collection');
  $handler->display->display_options['defaults']['arguments'] = FALSE;
  /* Contextual filter: Content: Collection (field_og_collection_ref) */
  $handler->display->display_options['arguments']['field_og_collection_ref_target_id']['id'] = 'field_og_collection_ref_target_id';
  $handler->display->display_options['arguments']['field_og_collection_ref_target_id']['table'] = 'og_membership';
  $handler->display->display_options['arguments']['field_og_collection_ref_target_id']['field'] = 'field_og_collection_ref_target_id';
  $handler->display->display_options['arguments']['field_og_collection_ref_target_id']['default_action'] = 'default';
  $handler->display->display_options['arguments']['field_og_collection_ref_target_id']['default_argument_type'] = 'node';
  $handler->display->display_options['arguments']['field_og_collection_ref_target_id']['summary']['number_of_records'] = '0';
  $handler->display->display_options['arguments']['field_og_collection_ref_target_id']['summary']['format'] = 'default_summary';
  $handler->display->display_options['arguments']['field_og_collection_ref_target_id']['summary_options']['items_per_page'] = '25';
  $handler->display->display_options['arguments']['field_og_collection_ref_target_id']['break_phrase'] = TRUE;
  $handler->display->display_options['path'] = 'alltexts_open/collections/%';

  /* Display: Front Page */
  $handler = $view->new_display('panel_pane', 'Front Page', 'panel_pane_1');
  $handler->display->display_options['defaults']['fields'] = FALSE;
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'node';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['alter']['alter_text'] = TRUE;
  $handler->display->display_options['fields']['title']['alter']['text'] = '<h3><i class="icon shanticon-texts"></i>[title]</h3>';
  $handler->display->display_options['fields']['title']['alter']['word_boundary'] = FALSE;
  $handler->display->display_options['fields']['title']['alter']['ellipsis'] = FALSE;
  $handler->display->display_options['fields']['title']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['title']['element_wrapper_class'] = 'book-view-card-title';
  /* Field: Content: Author */
  $handler->display->display_options['fields']['field_book_author']['id'] = 'field_book_author';
  $handler->display->display_options['fields']['field_book_author']['table'] = 'field_data_field_book_author';
  $handler->display->display_options['fields']['field_book_author']['field'] = 'field_book_author';
  $handler->display->display_options['fields']['field_book_author']['label'] = '';
  $handler->display->display_options['fields']['field_book_author']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_book_author']['delta_offset'] = '0';
  /* Field: Content: Original publication year */
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['id'] = 'field_dc_date_orginial_year';
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['table'] = 'field_data_field_dc_date_orginial_year';
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['field'] = 'field_dc_date_orginial_year';
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['label'] = '';
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['exclude'] = TRUE;
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['alter']['alter_text'] = TRUE;
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['alter']['text'] = '[[field_dc_date_orginial_year]]';
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['settings'] = array(
    'format_type' => 'long',
    'fromto' => 'both',
    'multiple_number' => '',
    'multiple_from' => '',
    'multiple_to' => '',
  );
  /* Field: Content: Publication year */
  $handler->display->display_options['fields']['field_dc_date_publication_year']['id'] = 'field_dc_date_publication_year';
  $handler->display->display_options['fields']['field_dc_date_publication_year']['table'] = 'field_data_field_dc_date_publication_year';
  $handler->display->display_options['fields']['field_dc_date_publication_year']['field'] = 'field_dc_date_publication_year';
  $handler->display->display_options['fields']['field_dc_date_publication_year']['label'] = '';
  $handler->display->display_options['fields']['field_dc_date_publication_year']['alter']['alter_text'] = TRUE;
  $handler->display->display_options['fields']['field_dc_date_publication_year']['alter']['text'] = '[field_dc_date_publication_year] [field_dc_date_orginial_year]';
  $handler->display->display_options['fields']['field_dc_date_publication_year']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_dc_date_publication_year']['settings'] = array(
    'format_type' => 'long',
    'fromto' => 'both',
    'multiple_number' => '',
    'multiple_from' => '',
    'multiple_to' => '',
  );
  /* Field: Content: Description */
  $handler->display->display_options['fields']['field_dc_description']['id'] = 'field_dc_description';
  $handler->display->display_options['fields']['field_dc_description']['table'] = 'field_data_field_dc_description';
  $handler->display->display_options['fields']['field_dc_description']['field'] = 'field_dc_description';
  $handler->display->display_options['fields']['field_dc_description']['label'] = '';
  $handler->display->display_options['fields']['field_dc_description']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_dc_description']['element_wrapper_class'] = 'book-view-card-desc';
  $handler->display->display_options['fields']['field_dc_description']['type'] = 'text_summary_or_trimmed';
  $handler->display->display_options['fields']['field_dc_description']['settings'] = array(
    'trim_length' => '600',
  );
  /* Field: Content: Collection */
  $handler->display->display_options['fields']['field_og_collection_ref']['id'] = 'field_og_collection_ref';
  $handler->display->display_options['fields']['field_og_collection_ref']['table'] = 'og_membership';
  $handler->display->display_options['fields']['field_og_collection_ref']['field'] = 'field_og_collection_ref';
  $handler->display->display_options['fields']['field_og_collection_ref']['label'] = '';
  $handler->display->display_options['fields']['field_og_collection_ref']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_og_collection_ref']['settings'] = array(
    'link' => 1,
  );
  $handler->display->display_options['pane_description'] = 'View All Texts';
  $handler->display->display_options['allow']['use_pager'] = 'use_pager';
  $handler->display->display_options['allow']['items_per_page'] = 'items_per_page';
  $handler->display->display_options['allow']['offset'] = 0;
  $handler->display->display_options['allow']['link_to_view'] = 0;
  $handler->display->display_options['allow']['more_link'] = 0;
  $handler->display->display_options['allow']['path_override'] = 0;
  $handler->display->display_options['allow']['title_override'] = 'title_override';
  $handler->display->display_options['allow']['exposed_form'] = 0;
  $handler->display->display_options['allow']['fields_override'] = 0;
  $handler->display->display_options['argument_input'] = array(
    'nid' => array(
      'type' => 'context',
      'context' => 'entity:node.nid',
      'context_optional' => 0,
      'panel' => '0',
      'fixed' => '',
      'label' => 'Content: Nid',
    ),
  );
  $handler->display->display_options['inherit_panels_path'] = '1';
  $export['all_texts_open'] = $view;

  $view = new view();
  $view->name = 'full_text_local';
  $view->description = '';
  $view->tag = 'default';
  $view->base_table = 'search_api_index_full_text_local';
  $view->human_name = 'Full Text Local';
  $view->core = 7;
  $view->api_version = '3.0';
  $view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */

  /* Display: Master */
  $handler = $view->new_display('default', 'Master', 'default');
  $handler->display->display_options['title'] = 'Full Text Local';
  $handler->display->display_options['css_class'] = 'view-full-text';
  $handler->display->display_options['use_ajax'] = TRUE;
  $handler->display->display_options['use_more_always'] = FALSE;
  $handler->display->display_options['access']['type'] = 'perm';
  $handler->display->display_options['cache']['type'] = 'none';
  $handler->display->display_options['query']['type'] = 'views_query';
  $handler->display->display_options['query']['options']['search_api_bypass_access'] = 0;
  $handler->display->display_options['query']['options']['entity_access'] = 0;
  $handler->display->display_options['exposed_form']['type'] = 'basic';
  $handler->display->display_options['exposed_form']['options']['submit_button'] = '&#8203;';
  $handler->display->display_options['exposed_form']['options']['reset_button'] = TRUE;
  $handler->display->display_options['exposed_form']['options']['expose_sort_order'] = FALSE;
  $handler->display->display_options['pager']['type'] = 'pagerer';
  $handler->display->display_options['pager']['options']['items_per_page'] = '10';
  $handler->display->display_options['pager']['options']['offset'] = '0';
  $handler->display->display_options['pager']['options']['id'] = '0';
  $handler->display->display_options['pager']['options']['quantity'] = '9';
  $handler->display->display_options['pager']['options']['preset'] = 'shanti_default';
  $handler->display->display_options['style_plugin'] = 'default';
  $handler->display->display_options['style_options']['default_row_class'] = FALSE;
  $handler->display->display_options['style_options']['row_class_special'] = FALSE;
  $handler->display->display_options['row_plugin'] = 'fields';
  $handler->display->display_options['row_options']['default_field_elements'] = FALSE;
  /* No results behavior: Global: Text area */
  $handler->display->display_options['empty']['area']['id'] = 'area';
  $handler->display->display_options['empty']['area']['table'] = 'views';
  $handler->display->display_options['empty']['area']['field'] = 'area';
  $handler->display->display_options['empty']['area']['empty'] = TRUE;
  $handler->display->display_options['empty']['area']['content'] = '<p>Enter a search string, consisting of a word or a phrase enclosed in quotes, to find matching text content.</p>';
  $handler->display->display_options['empty']['area']['format'] = 'full_html';
  /* Field: Node ID */
  $handler->display->display_options['fields']['nid']['id'] = 'nid';
  $handler->display->display_options['fields']['nid']['table'] = 'search_api_index_full_text_local';
  $handler->display->display_options['fields']['nid']['field'] = 'nid';
  $handler->display->display_options['fields']['nid']['ui_name'] = 'Node ID';
  $handler->display->display_options['fields']['nid']['label'] = '';
  $handler->display->display_options['fields']['nid']['exclude'] = TRUE;
  $handler->display->display_options['fields']['nid']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['nid']['element_default_classes'] = FALSE;
  $handler->display->display_options['fields']['nid']['separator'] = '';
  $handler->display->display_options['fields']['nid']['link_to_entity'] = 0;
  /* Field: Ancestors */
  $handler->display->display_options['fields']['book_ancestors']['id'] = 'book_ancestors';
  $handler->display->display_options['fields']['book_ancestors']['table'] = 'search_api_index_full_text_local';
  $handler->display->display_options['fields']['book_ancestors']['field'] = 'book_ancestors';
  $handler->display->display_options['fields']['book_ancestors']['ui_name'] = 'Ancestors';
  $handler->display->display_options['fields']['book_ancestors']['label'] = '';
  $handler->display->display_options['fields']['book_ancestors']['exclude'] = TRUE;
  $handler->display->display_options['fields']['book_ancestors']['alter']['alter_text'] = TRUE;
  $handler->display->display_options['fields']['book_ancestors']['alter']['text'] = '[book_ancestors] >';
  $handler->display->display_options['fields']['book_ancestors']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['book_ancestors']['element_default_classes'] = FALSE;
  $handler->display->display_options['fields']['book_ancestors']['list']['separator'] = ' > ';
  $handler->display->display_options['fields']['book_ancestors']['link_to_entity'] = 0;
  $handler->display->display_options['fields']['book_ancestors']['view_mode'] = 'full';
  $handler->display->display_options['fields']['book_ancestors']['bypass_access'] = 0;
  /* Field: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'search_api_index_full_text_local';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['ui_name'] = 'Title';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['exclude'] = TRUE;
  $handler->display->display_options['fields']['title']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['title']['element_default_classes'] = FALSE;
  $handler->display->display_options['fields']['title']['link_to_entity'] = 0;
  /* Field: Excerpt */
  $handler->display->display_options['fields']['search_api_excerpt']['id'] = 'search_api_excerpt';
  $handler->display->display_options['fields']['search_api_excerpt']['table'] = 'search_api_index_full_text_local';
  $handler->display->display_options['fields']['search_api_excerpt']['field'] = 'search_api_excerpt';
  $handler->display->display_options['fields']['search_api_excerpt']['ui_name'] = 'Excerpt';
  $handler->display->display_options['fields']['search_api_excerpt']['label'] = '';
  $handler->display->display_options['fields']['search_api_excerpt']['exclude'] = TRUE;
  $handler->display->display_options['fields']['search_api_excerpt']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['search_api_excerpt']['element_default_classes'] = FALSE;
  $handler->display->display_options['fields']['search_api_excerpt']['link_to_entity'] = 0;
  /* Field: Search Term */
  $handler->display->display_options['fields']['php']['id'] = 'php';
  $handler->display->display_options['fields']['php']['table'] = 'views';
  $handler->display->display_options['fields']['php']['field'] = 'php';
  $handler->display->display_options['fields']['php']['ui_name'] = 'Search Term';
  $handler->display->display_options['fields']['php']['label'] = '';
  $handler->display->display_options['fields']['php']['exclude'] = TRUE;
  $handler->display->display_options['fields']['php']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['php']['element_default_classes'] = FALSE;
  $handler->display->display_options['fields']['php']['hide_alter_empty'] = FALSE;
  $handler->display->display_options['fields']['php']['use_php_setup'] = 1;
  $handler->display->display_options['fields']['php']['php_setup'] = '$static = $view->exposed_input[\'search_api_views_fulltext\'];';
  $handler->display->display_options['fields']['php']['php_value'] = 'return $static;';
  $handler->display->display_options['fields']['php']['php_output'] = '<?php echo $value; ?>';
  $handler->display->display_options['fields']['php']['use_php_click_sortable'] = '0';
  $handler->display->display_options['fields']['php']['php_click_sortable'] = '';
  /* Field: Result */
  $handler->display->display_options['fields']['nothing']['id'] = 'nothing';
  $handler->display->display_options['fields']['nothing']['table'] = 'views';
  $handler->display->display_options['fields']['nothing']['field'] = 'nothing';
  $handler->display->display_options['fields']['nothing']['ui_name'] = 'Result';
  $handler->display->display_options['fields']['nothing']['label'] = '';
  $handler->display->display_options['fields']['nothing']['alter']['text'] = '<h3>[book_ancestors] <a href="/node/[nid]?s=[php]">[title]</a></h3>
<p>[search_api_excerpt]</p>';
  $handler->display->display_options['fields']['nothing']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['nothing']['element_default_classes'] = FALSE;
  /* Sort criterion: Search: Relevance */
  $handler->display->display_options['sorts']['search_api_relevance']['id'] = 'search_api_relevance';
  $handler->display->display_options['sorts']['search_api_relevance']['table'] = 'search_api_index_full_text_local';
  $handler->display->display_options['sorts']['search_api_relevance']['field'] = 'search_api_relevance';
  /* Filter criterion: Search: Fulltext search */
  $handler->display->display_options['filters']['search_api_views_fulltext']['id'] = 'search_api_views_fulltext';
  $handler->display->display_options['filters']['search_api_views_fulltext']['table'] = 'search_api_index_full_text_local';
  $handler->display->display_options['filters']['search_api_views_fulltext']['field'] = 'search_api_views_fulltext';
  $handler->display->display_options['filters']['search_api_views_fulltext']['exposed'] = TRUE;
  $handler->display->display_options['filters']['search_api_views_fulltext']['expose']['operator_id'] = 'search_api_views_fulltext_op';
  $handler->display->display_options['filters']['search_api_views_fulltext']['expose']['operator'] = 'search_api_views_fulltext_op';
  $handler->display->display_options['filters']['search_api_views_fulltext']['expose']['identifier'] = 'search_api_views_fulltext';
  $handler->display->display_options['filters']['search_api_views_fulltext']['expose']['required'] = TRUE;
  $handler->display->display_options['filters']['search_api_views_fulltext']['expose']['remember_roles'] = array(
    2 => '2',
    1 => 0,
    3 => 0,
  );
  $handler->display->display_options['filters']['search_api_views_fulltext']['fields'] = array(
    'field_book_content:value' => 'field_book_content:value',
  );

  /* Display: Block */
  $handler = $view->new_display('block', 'Block', 'block');
  $handler->display->display_options['block_description'] = 'Full Text Search';
  $handler->display->display_options['block_caching'] = '-1';

  /* Display: Block (no PHP) */
  $handler = $view->new_display('block', 'Block (no PHP)', 'block_1');
  $handler->display->display_options['defaults']['fields'] = FALSE;
  /* Field: Node ID */
  $handler->display->display_options['fields']['nid']['id'] = 'nid';
  $handler->display->display_options['fields']['nid']['table'] = 'search_api_index_full_text_local';
  $handler->display->display_options['fields']['nid']['field'] = 'nid';
  $handler->display->display_options['fields']['nid']['ui_name'] = 'Node ID';
  $handler->display->display_options['fields']['nid']['label'] = '';
  $handler->display->display_options['fields']['nid']['exclude'] = TRUE;
  $handler->display->display_options['fields']['nid']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['nid']['element_default_classes'] = FALSE;
  $handler->display->display_options['fields']['nid']['separator'] = '';
  $handler->display->display_options['fields']['nid']['link_to_entity'] = 0;
  /* Field: Ancestors */
  $handler->display->display_options['fields']['book_ancestors']['id'] = 'book_ancestors';
  $handler->display->display_options['fields']['book_ancestors']['table'] = 'search_api_index_full_text_local';
  $handler->display->display_options['fields']['book_ancestors']['field'] = 'book_ancestors';
  $handler->display->display_options['fields']['book_ancestors']['ui_name'] = 'Ancestors';
  $handler->display->display_options['fields']['book_ancestors']['label'] = '';
  $handler->display->display_options['fields']['book_ancestors']['exclude'] = TRUE;
  $handler->display->display_options['fields']['book_ancestors']['alter']['alter_text'] = TRUE;
  $handler->display->display_options['fields']['book_ancestors']['alter']['text'] = '[book_ancestors] >';
  $handler->display->display_options['fields']['book_ancestors']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['book_ancestors']['element_default_classes'] = FALSE;
  $handler->display->display_options['fields']['book_ancestors']['list']['separator'] = ' > ';
  $handler->display->display_options['fields']['book_ancestors']['link_to_entity'] = 0;
  $handler->display->display_options['fields']['book_ancestors']['view_mode'] = 'full';
  $handler->display->display_options['fields']['book_ancestors']['bypass_access'] = 0;
  /* Field: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'search_api_index_full_text_local';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['ui_name'] = 'Title';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['exclude'] = TRUE;
  $handler->display->display_options['fields']['title']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['title']['element_default_classes'] = FALSE;
  $handler->display->display_options['fields']['title']['link_to_entity'] = 0;
  /* Field: Excerpt */
  $handler->display->display_options['fields']['search_api_excerpt']['id'] = 'search_api_excerpt';
  $handler->display->display_options['fields']['search_api_excerpt']['table'] = 'search_api_index_full_text_local';
  $handler->display->display_options['fields']['search_api_excerpt']['field'] = 'search_api_excerpt';
  $handler->display->display_options['fields']['search_api_excerpt']['ui_name'] = 'Excerpt';
  $handler->display->display_options['fields']['search_api_excerpt']['label'] = '';
  $handler->display->display_options['fields']['search_api_excerpt']['exclude'] = TRUE;
  $handler->display->display_options['fields']['search_api_excerpt']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['search_api_excerpt']['element_default_classes'] = FALSE;
  $handler->display->display_options['fields']['search_api_excerpt']['link_to_entity'] = 0;
  /* Field: Result */
  $handler->display->display_options['fields']['nothing']['id'] = 'nothing';
  $handler->display->display_options['fields']['nothing']['table'] = 'views';
  $handler->display->display_options['fields']['nothing']['field'] = 'nothing';
  $handler->display->display_options['fields']['nothing']['ui_name'] = 'Result';
  $handler->display->display_options['fields']['nothing']['label'] = '';
  $handler->display->display_options['fields']['nothing']['alter']['text'] = '<!-- __SEARCHTERM__ is replaced by the value of the search input filter in the template for this field -->
<h3>[book_ancestors] <a href="/node/[nid]?s=__SEARCHTERM__">[title]</a></h3>
<p>[search_api_excerpt]</p>';
  $handler->display->display_options['fields']['nothing']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['nothing']['element_default_classes'] = FALSE;
  $export['full_text_local'] = $view;

  $view = new view();
  $view->name = 'full_text_solr';
  $view->description = '';
  $view->tag = 'default';
  $view->base_table = 'search_api_index_full_text_solr';
  $view->human_name = 'Full Text Solr';
  $view->core = 7;
  $view->api_version = '3.0';
  $view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */

  /* Display: Master */
  $handler = $view->new_display('default', 'Master', 'default');
  $handler->display->display_options['title'] = 'Full Text Solr';
  $handler->display->display_options['css_class'] = 'view-full-text';
  $handler->display->display_options['use_ajax'] = TRUE;
  $handler->display->display_options['use_more_always'] = FALSE;
  $handler->display->display_options['access']['type'] = 'perm';
  $handler->display->display_options['cache']['type'] = 'none';
  $handler->display->display_options['query']['type'] = 'views_query';
  $handler->display->display_options['query']['options']['search_api_bypass_access'] = 0;
  $handler->display->display_options['query']['options']['entity_access'] = 0;
  $handler->display->display_options['query']['options']['parse_mode'] = 'direct';
  $handler->display->display_options['exposed_form']['type'] = 'basic';
  $handler->display->display_options['exposed_form']['options']['submit_button'] = '&#8203;';
  $handler->display->display_options['exposed_form']['options']['reset_button'] = TRUE;
  $handler->display->display_options['exposed_form']['options']['expose_sort_order'] = FALSE;
  $handler->display->display_options['pager']['type'] = 'pagerer';
  $handler->display->display_options['pager']['options']['items_per_page'] = '10';
  $handler->display->display_options['pager']['options']['offset'] = '0';
  $handler->display->display_options['pager']['options']['id'] = '0';
  $handler->display->display_options['pager']['options']['quantity'] = '5';
  $handler->display->display_options['pager']['options']['preset'] = 'shanti_default';
  $handler->display->display_options['style_plugin'] = 'default';
  $handler->display->display_options['style_options']['default_row_class'] = FALSE;
  $handler->display->display_options['style_options']['row_class_special'] = FALSE;
  $handler->display->display_options['row_plugin'] = 'fields';
  $handler->display->display_options['row_options']['inline'] = array(
    'book_ancestors' => 'book_ancestors',
    'title' => 'title',
  );
  $handler->display->display_options['row_options']['separator'] = ' > ';
  $handler->display->display_options['row_options']['default_field_elements'] = FALSE;
  /* No results behavior: Global: Text area */
  $handler->display->display_options['empty']['area']['id'] = 'area';
  $handler->display->display_options['empty']['area']['table'] = 'views';
  $handler->display->display_options['empty']['area']['field'] = 'area';
  $handler->display->display_options['empty']['area']['empty'] = TRUE;
  $handler->display->display_options['empty']['area']['content'] = '<p>Enter a search string, consisting of a word or a phrase enclosed in quotes, to find matching text content.</p>';
  $handler->display->display_options['empty']['area']['format'] = 'full_html';
  /* Field: Search Term */
  $handler->display->display_options['fields']['php']['id'] = 'php';
  $handler->display->display_options['fields']['php']['table'] = 'views';
  $handler->display->display_options['fields']['php']['field'] = 'php';
  $handler->display->display_options['fields']['php']['ui_name'] = 'Search Term';
  $handler->display->display_options['fields']['php']['label'] = '';
  $handler->display->display_options['fields']['php']['exclude'] = TRUE;
  $handler->display->display_options['fields']['php']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['php']['element_default_classes'] = FALSE;
  $handler->display->display_options['fields']['php']['use_php_setup'] = 1;
  $handler->display->display_options['fields']['php']['php_setup'] = '$static = $view->exposed_input[\'search_api_views_fulltext\'];';
  $handler->display->display_options['fields']['php']['php_output'] = '<?php echo $static; ?>';
  $handler->display->display_options['fields']['php']['use_php_click_sortable'] = '0';
  $handler->display->display_options['fields']['php']['php_click_sortable'] = '';
  /* Field: Node ID */
  $handler->display->display_options['fields']['nid']['id'] = 'nid';
  $handler->display->display_options['fields']['nid']['table'] = 'search_api_index_full_text_solr';
  $handler->display->display_options['fields']['nid']['field'] = 'nid';
  $handler->display->display_options['fields']['nid']['ui_name'] = 'Node ID';
  $handler->display->display_options['fields']['nid']['label'] = '';
  $handler->display->display_options['fields']['nid']['exclude'] = TRUE;
  $handler->display->display_options['fields']['nid']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['nid']['element_default_classes'] = FALSE;
  $handler->display->display_options['fields']['nid']['separator'] = '';
  $handler->display->display_options['fields']['nid']['link_to_entity'] = 0;
  /* Field: Ancestors */
  $handler->display->display_options['fields']['book_ancestors']['id'] = 'book_ancestors';
  $handler->display->display_options['fields']['book_ancestors']['table'] = 'search_api_index_full_text_solr';
  $handler->display->display_options['fields']['book_ancestors']['field'] = 'book_ancestors';
  $handler->display->display_options['fields']['book_ancestors']['ui_name'] = 'Ancestors';
  $handler->display->display_options['fields']['book_ancestors']['label'] = '';
  $handler->display->display_options['fields']['book_ancestors']['exclude'] = TRUE;
  $handler->display->display_options['fields']['book_ancestors']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['book_ancestors']['element_default_classes'] = FALSE;
  $handler->display->display_options['fields']['book_ancestors']['list']['separator'] = ' > ';
  $handler->display->display_options['fields']['book_ancestors']['link_to_entity'] = 0;
  $handler->display->display_options['fields']['book_ancestors']['view_mode'] = 'full';
  $handler->display->display_options['fields']['book_ancestors']['bypass_access'] = 0;
  /* Field: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'search_api_index_full_text_solr';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['ui_name'] = 'Title';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['exclude'] = TRUE;
  $handler->display->display_options['fields']['title']['alter']['text'] = '<a href="/node/[nid]?s=[php]">[title]</a>';
  $handler->display->display_options['fields']['title']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['title']['element_default_classes'] = FALSE;
  $handler->display->display_options['fields']['title']['link_to_entity'] = 0;
  /* Field: Excerpt */
  $handler->display->display_options['fields']['search_api_excerpt']['id'] = 'search_api_excerpt';
  $handler->display->display_options['fields']['search_api_excerpt']['table'] = 'search_api_index_full_text_solr';
  $handler->display->display_options['fields']['search_api_excerpt']['field'] = 'search_api_excerpt';
  $handler->display->display_options['fields']['search_api_excerpt']['ui_name'] = 'Excerpt';
  $handler->display->display_options['fields']['search_api_excerpt']['label'] = '';
  $handler->display->display_options['fields']['search_api_excerpt']['alter']['alter_text'] = TRUE;
  $handler->display->display_options['fields']['search_api_excerpt']['alter']['text'] = '<h3>[book_ancestors] <a href="/node/[nid]?s=[php]">[title]</a></h3>
<p>[search_api_excerpt]</p>';
  $handler->display->display_options['fields']['search_api_excerpt']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['search_api_excerpt']['element_default_classes'] = FALSE;
  $handler->display->display_options['fields']['search_api_excerpt']['link_to_entity'] = 0;
  /* Field: Indexed Node: Places */
  $handler->display->display_options['fields']['field_kmap_places']['id'] = 'field_kmap_places';
  $handler->display->display_options['fields']['field_kmap_places']['table'] = 'search_api_index_full_text_solr';
  $handler->display->display_options['fields']['field_kmap_places']['field'] = 'field_kmap_places';
  $handler->display->display_options['fields']['field_kmap_places']['click_sort_column'] = 'raw';
  $handler->display->display_options['fields']['field_kmap_places']['settings'] = array(
    'target' => '_blank',
  );
  $handler->display->display_options['fields']['field_kmap_places']['delta_offset'] = '0';
  /* Field: Indexed Node: Subjects */
  $handler->display->display_options['fields']['field_kmap_term']['id'] = 'field_kmap_term';
  $handler->display->display_options['fields']['field_kmap_term']['table'] = 'search_api_index_full_text_solr';
  $handler->display->display_options['fields']['field_kmap_term']['field'] = 'field_kmap_term';
  $handler->display->display_options['fields']['field_kmap_term']['click_sort_column'] = 'raw';
  $handler->display->display_options['fields']['field_kmap_term']['settings'] = array(
    'target' => '_blank',
  );
  $handler->display->display_options['fields']['field_kmap_term']['delta_offset'] = '0';
  /* Sort criterion: Search: Relevance */
  $handler->display->display_options['sorts']['search_api_relevance']['id'] = 'search_api_relevance';
  $handler->display->display_options['sorts']['search_api_relevance']['table'] = 'search_api_index_full_text_solr';
  $handler->display->display_options['sorts']['search_api_relevance']['field'] = 'search_api_relevance';
  /* Filter criterion: Search: Fulltext search */
  $handler->display->display_options['filters']['search_api_views_fulltext']['id'] = 'search_api_views_fulltext';
  $handler->display->display_options['filters']['search_api_views_fulltext']['table'] = 'search_api_index_full_text_solr';
  $handler->display->display_options['filters']['search_api_views_fulltext']['field'] = 'search_api_views_fulltext';
  $handler->display->display_options['filters']['search_api_views_fulltext']['group'] = 1;
  $handler->display->display_options['filters']['search_api_views_fulltext']['exposed'] = TRUE;
  $handler->display->display_options['filters']['search_api_views_fulltext']['expose']['operator_id'] = 'search_api_views_fulltext_op';
  $handler->display->display_options['filters']['search_api_views_fulltext']['expose']['operator'] = 'search_api_views_fulltext_op';
  $handler->display->display_options['filters']['search_api_views_fulltext']['expose']['identifier'] = 'search_api_views_fulltext';
  $handler->display->display_options['filters']['search_api_views_fulltext']['expose']['required'] = TRUE;
  $handler->display->display_options['filters']['search_api_views_fulltext']['expose']['remember_roles'] = array(
    2 => '2',
    1 => 0,
    3 => 0,
  );
  $handler->display->display_options['filters']['search_api_views_fulltext']['fields'] = array(
    'field_book_content:value' => 'field_book_content:value',
  );

  /* Display: Block */
  $handler = $view->new_display('block', 'Block', 'block');
  $handler->display->display_options['block_description'] = 'Full Text Solr';

  /* Display: Block (no PHP) */
  $handler = $view->new_display('block', 'Block (no PHP)', 'block_1');
  $handler->display->display_options['defaults']['fields'] = FALSE;
  /* Field: Node ID */
  $handler->display->display_options['fields']['nid']['id'] = 'nid';
  $handler->display->display_options['fields']['nid']['table'] = 'search_api_index_full_text_solr';
  $handler->display->display_options['fields']['nid']['field'] = 'nid';
  $handler->display->display_options['fields']['nid']['ui_name'] = 'Node ID';
  $handler->display->display_options['fields']['nid']['label'] = '';
  $handler->display->display_options['fields']['nid']['exclude'] = TRUE;
  $handler->display->display_options['fields']['nid']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['nid']['element_default_classes'] = FALSE;
  $handler->display->display_options['fields']['nid']['separator'] = '';
  $handler->display->display_options['fields']['nid']['link_to_entity'] = 0;
  /* Field: Ancestors */
  $handler->display->display_options['fields']['book_ancestors']['id'] = 'book_ancestors';
  $handler->display->display_options['fields']['book_ancestors']['table'] = 'search_api_index_full_text_solr';
  $handler->display->display_options['fields']['book_ancestors']['field'] = 'book_ancestors';
  $handler->display->display_options['fields']['book_ancestors']['ui_name'] = 'Ancestors';
  $handler->display->display_options['fields']['book_ancestors']['label'] = '';
  $handler->display->display_options['fields']['book_ancestors']['exclude'] = TRUE;
  $handler->display->display_options['fields']['book_ancestors']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['book_ancestors']['element_default_classes'] = FALSE;
  $handler->display->display_options['fields']['book_ancestors']['list']['separator'] = ' > ';
  $handler->display->display_options['fields']['book_ancestors']['link_to_entity'] = 0;
  $handler->display->display_options['fields']['book_ancestors']['view_mode'] = 'full';
  $handler->display->display_options['fields']['book_ancestors']['bypass_access'] = 0;
  /* Field: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'search_api_index_full_text_solr';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['ui_name'] = 'Title';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['exclude'] = TRUE;
  $handler->display->display_options['fields']['title']['alter']['text'] = '<a href="/node/[nid]?s=[php]">[title]</a>';
  $handler->display->display_options['fields']['title']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['title']['element_default_classes'] = FALSE;
  $handler->display->display_options['fields']['title']['link_to_entity'] = 0;
  /* Field: Excerpt */
  $handler->display->display_options['fields']['search_api_excerpt']['id'] = 'search_api_excerpt';
  $handler->display->display_options['fields']['search_api_excerpt']['table'] = 'search_api_index_full_text_solr';
  $handler->display->display_options['fields']['search_api_excerpt']['field'] = 'search_api_excerpt';
  $handler->display->display_options['fields']['search_api_excerpt']['ui_name'] = 'Excerpt';
  $handler->display->display_options['fields']['search_api_excerpt']['label'] = '';
  $handler->display->display_options['fields']['search_api_excerpt']['alter']['alter_text'] = TRUE;
  $handler->display->display_options['fields']['search_api_excerpt']['alter']['text'] = '<h3>[book_ancestors] <a href="/node/[nid]?s=">[title]</a></h3>
<p>[search_api_excerpt]</p>';
  $handler->display->display_options['fields']['search_api_excerpt']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['search_api_excerpt']['element_default_classes'] = FALSE;
  $handler->display->display_options['fields']['search_api_excerpt']['link_to_entity'] = 0;

  /* Display: Page */
  $handler = $view->new_display('page', 'Page', 'page_1');
  $handler->display->display_options['defaults']['filter_groups'] = FALSE;
  $handler->display->display_options['defaults']['filters'] = FALSE;
  /* Filter criterion: Search: Fulltext search */
  $handler->display->display_options['filters']['search_api_views_fulltext']['id'] = 'search_api_views_fulltext';
  $handler->display->display_options['filters']['search_api_views_fulltext']['table'] = 'search_api_index_full_text_solr';
  $handler->display->display_options['filters']['search_api_views_fulltext']['field'] = 'search_api_views_fulltext';
  $handler->display->display_options['filters']['search_api_views_fulltext']['group'] = 1;
  $handler->display->display_options['filters']['search_api_views_fulltext']['exposed'] = TRUE;
  $handler->display->display_options['filters']['search_api_views_fulltext']['expose']['operator_id'] = 'search_api_views_fulltext_op';
  $handler->display->display_options['filters']['search_api_views_fulltext']['expose']['operator'] = 'search_api_views_fulltext_op';
  $handler->display->display_options['filters']['search_api_views_fulltext']['expose']['identifier'] = 'search_api_views_fulltext';
  $handler->display->display_options['filters']['search_api_views_fulltext']['expose']['remember_roles'] = array(
    2 => '2',
    1 => 0,
    3 => 0,
  );
  $handler->display->display_options['filters']['search_api_views_fulltext']['fields'] = array(
    'field_book_content:value' => 'field_book_content:value',
  );
  /* Filter criterion: Indexed Node: Author */
  $handler->display->display_options['filters']['field_book_author']['id'] = 'field_book_author';
  $handler->display->display_options['filters']['field_book_author']['table'] = 'search_api_index_full_text_solr';
  $handler->display->display_options['filters']['field_book_author']['field'] = 'field_book_author';
  $handler->display->display_options['filters']['field_book_author']['group'] = 1;
  $handler->display->display_options['filters']['field_book_author']['exposed'] = TRUE;
  $handler->display->display_options['filters']['field_book_author']['expose']['operator_id'] = 'field_book_author_op';
  $handler->display->display_options['filters']['field_book_author']['expose']['label'] = 'Author';
  $handler->display->display_options['filters']['field_book_author']['expose']['operator'] = 'field_book_author_op';
  $handler->display->display_options['filters']['field_book_author']['expose']['identifier'] = 'field_book_author';
  $handler->display->display_options['filters']['field_book_author']['expose']['remember_roles'] = array(
    2 => '2',
    1 => 0,
    3 => 0,
  );
  /* Filter criterion: Broken/missing handler */
  $handler->display->display_options['filters']['field_kmap_places']['id'] = 'field_kmap_places';
  $handler->display->display_options['filters']['field_kmap_places']['table'] = 'search_api_index_full_text_solr';
  $handler->display->display_options['filters']['field_kmap_places']['field'] = 'field_kmap_places';
  $handler->display->display_options['filters']['field_kmap_places']['group'] = 1;
  $handler->display->display_options['filters']['field_kmap_places']['exposed'] = TRUE;
  $handler->display->display_options['filters']['field_kmap_places']['expose']['operator_id'] = 'field_kmap_places_op';
  $handler->display->display_options['filters']['field_kmap_places']['expose']['label'] = 'Places';
  $handler->display->display_options['filters']['field_kmap_places']['expose']['operator'] = 'field_kmap_places_op';
  $handler->display->display_options['filters']['field_kmap_places']['expose']['identifier'] = 'field_kmap_places';
  $handler->display->display_options['filters']['field_kmap_places']['expose']['remember_roles'] = array(
    2 => '2',
    1 => 0,
    3 => 0,
  );
  /* Filter criterion: Broken/missing handler */
  $handler->display->display_options['filters']['field_kmap_term']['id'] = 'field_kmap_term';
  $handler->display->display_options['filters']['field_kmap_term']['table'] = 'search_api_index_full_text_solr';
  $handler->display->display_options['filters']['field_kmap_term']['field'] = 'field_kmap_term';
  $handler->display->display_options['filters']['field_kmap_term']['group'] = 1;
  $handler->display->display_options['filters']['field_kmap_term']['exposed'] = TRUE;
  $handler->display->display_options['filters']['field_kmap_term']['expose']['operator_id'] = 'field_kmap_term_op';
  $handler->display->display_options['filters']['field_kmap_term']['expose']['label'] = 'Subjects';
  $handler->display->display_options['filters']['field_kmap_term']['expose']['operator'] = 'field_kmap_term_op';
  $handler->display->display_options['filters']['field_kmap_term']['expose']['identifier'] = 'field_kmap_term';
  $handler->display->display_options['filters']['field_kmap_term']['expose']['remember_roles'] = array(
    2 => '2',
    1 => 0,
    3 => 0,
  );
  /* Filter criterion: Indexed Node: Original publication year */
  $handler->display->display_options['filters']['field_dc_date_orginial_year']['id'] = 'field_dc_date_orginial_year';
  $handler->display->display_options['filters']['field_dc_date_orginial_year']['table'] = 'search_api_index_full_text_solr';
  $handler->display->display_options['filters']['field_dc_date_orginial_year']['field'] = 'field_dc_date_orginial_year';
  $handler->display->display_options['filters']['field_dc_date_orginial_year']['group'] = 1;
  $handler->display->display_options['filters']['field_dc_date_orginial_year']['exposed'] = TRUE;
  $handler->display->display_options['filters']['field_dc_date_orginial_year']['expose']['operator_id'] = 'field_dc_date_orginial_year_op';
  $handler->display->display_options['filters']['field_dc_date_orginial_year']['expose']['label'] = 'Original publication year';
  $handler->display->display_options['filters']['field_dc_date_orginial_year']['expose']['operator'] = 'field_dc_date_orginial_year_op';
  $handler->display->display_options['filters']['field_dc_date_orginial_year']['expose']['identifier'] = 'field_dc_date_orginial_year';
  $handler->display->display_options['filters']['field_dc_date_orginial_year']['expose']['remember_roles'] = array(
    2 => '2',
    1 => 0,
    3 => 0,
  );
  /* Filter criterion: Indexed Node: Publication year */
  $handler->display->display_options['filters']['field_dc_date_publication_year']['id'] = 'field_dc_date_publication_year';
  $handler->display->display_options['filters']['field_dc_date_publication_year']['table'] = 'search_api_index_full_text_solr';
  $handler->display->display_options['filters']['field_dc_date_publication_year']['field'] = 'field_dc_date_publication_year';
  $handler->display->display_options['filters']['field_dc_date_publication_year']['group'] = 1;
  $handler->display->display_options['filters']['field_dc_date_publication_year']['exposed'] = TRUE;
  $handler->display->display_options['filters']['field_dc_date_publication_year']['expose']['operator_id'] = 'field_dc_date_publication_year_op';
  $handler->display->display_options['filters']['field_dc_date_publication_year']['expose']['label'] = 'Publication year';
  $handler->display->display_options['filters']['field_dc_date_publication_year']['expose']['operator'] = 'field_dc_date_publication_year_op';
  $handler->display->display_options['filters']['field_dc_date_publication_year']['expose']['identifier'] = 'field_dc_date_publication_year';
  $handler->display->display_options['filters']['field_dc_date_publication_year']['expose']['remember_roles'] = array(
    2 => '2',
    1 => 0,
    3 => 0,
  );
  $handler->display->display_options['path'] = 'full-text-solr';
  $export['full_text_solr'] = $view;

  $view = new view();
  $view->name = 'single_text_body';
  $view->description = '';
  $view->tag = 'SHANTI Texts';
  $view->base_table = 'node';
  $view->human_name = 'Single Text Body';
  $view->core = 7;
  $view->api_version = '3.0';
  $view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */

  /* Display: Master */
  $handler = $view->new_display('default', 'Master', 'default');
  $handler->display->display_options['use_more_always'] = FALSE;
  $handler->display->display_options['access']['type'] = 'perm';
  $handler->display->display_options['cache']['type'] = 'none';
  $handler->display->display_options['query']['type'] = 'views_query';
  $handler->display->display_options['exposed_form']['type'] = 'basic';
  $handler->display->display_options['pager']['type'] = 'none';
  $handler->display->display_options['pager']['options']['offset'] = '0';
  $handler->display->display_options['style_plugin'] = 'default';
  $handler->display->display_options['style_options']['default_row_class'] = FALSE;
  $handler->display->display_options['style_options']['row_class_special'] = FALSE;
  $handler->display->display_options['row_plugin'] = 'fields';
  $handler->display->display_options['row_options']['default_field_elements'] = FALSE;
  /* Relationship: Book: Top level book */
  $handler->display->display_options['relationships']['bid']['id'] = 'bid';
  $handler->display->display_options['relationships']['bid']['table'] = 'book';
  $handler->display->display_options['relationships']['bid']['field'] = 'bid';
  $handler->display->display_options['relationships']['bid']['required'] = TRUE;
  /* Field: BID */
  $handler->display->display_options['fields']['nid_1']['id'] = 'nid_1';
  $handler->display->display_options['fields']['nid_1']['table'] = 'node';
  $handler->display->display_options['fields']['nid_1']['field'] = 'nid';
  $handler->display->display_options['fields']['nid_1']['relationship'] = 'bid';
  $handler->display->display_options['fields']['nid_1']['ui_name'] = 'BID';
  $handler->display->display_options['fields']['nid_1']['label'] = '';
  $handler->display->display_options['fields']['nid_1']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['nid_1']['element_default_classes'] = FALSE;
  /* Field: Content: Nid */
  $handler->display->display_options['fields']['nid']['id'] = 'nid';
  $handler->display->display_options['fields']['nid']['table'] = 'node';
  $handler->display->display_options['fields']['nid']['field'] = 'nid';
  $handler->display->display_options['fields']['nid']['label'] = '';
  $handler->display->display_options['fields']['nid']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['nid']['element_default_classes'] = FALSE;
  /* Field: Book: Depth */
  $handler->display->display_options['fields']['depth']['id'] = 'depth';
  $handler->display->display_options['fields']['depth']['table'] = 'book_menu_links';
  $handler->display->display_options['fields']['depth']['field'] = 'depth';
  $handler->display->display_options['fields']['depth']['label'] = '';
  $handler->display->display_options['fields']['depth']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['depth']['element_default_classes'] = FALSE;
  $handler->display->display_options['fields']['depth']['separator'] = '';
  /* Field: Book: Weight */
  $handler->display->display_options['fields']['weight']['id'] = 'weight';
  $handler->display->display_options['fields']['weight']['table'] = 'book_menu_links';
  $handler->display->display_options['fields']['weight']['field'] = 'weight';
  $handler->display->display_options['fields']['weight']['label'] = '';
  $handler->display->display_options['fields']['weight']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['weight']['element_default_classes'] = FALSE;
  $handler->display->display_options['fields']['weight']['separator'] = '';
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'node';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['alter']['text'] = '<a name="shanti-text-[nid]"></a>
<header class="shanti-text-header depth-[depth]"><h[depth]>[title]</h[depth]></header>';
  $handler->display->display_options['fields']['title']['alter']['word_boundary'] = FALSE;
  $handler->display->display_options['fields']['title']['alter']['ellipsis'] = FALSE;
  $handler->display->display_options['fields']['title']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['title']['element_default_classes'] = FALSE;
  $handler->display->display_options['fields']['title']['link_to_node'] = FALSE;
  /* Field: Collection NID */
  $handler->display->display_options['fields']['field_og_collection_ref_1']['id'] = 'field_og_collection_ref_1';
  $handler->display->display_options['fields']['field_og_collection_ref_1']['table'] = 'og_membership';
  $handler->display->display_options['fields']['field_og_collection_ref_1']['field'] = 'field_og_collection_ref';
  $handler->display->display_options['fields']['field_og_collection_ref_1']['ui_name'] = 'Collection NID';
  $handler->display->display_options['fields']['field_og_collection_ref_1']['label'] = '';
  $handler->display->display_options['fields']['field_og_collection_ref_1']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_og_collection_ref_1']['element_default_classes'] = FALSE;
  $handler->display->display_options['fields']['field_og_collection_ref_1']['type'] = 'entityreference_entity_id';
  $handler->display->display_options['fields']['field_og_collection_ref_1']['settings'] = array(
    'link' => 0,
  );
  /* Field: Content: Content */
  $handler->display->display_options['fields']['field_book_content']['id'] = 'field_book_content';
  $handler->display->display_options['fields']['field_book_content']['table'] = 'field_data_field_book_content';
  $handler->display->display_options['fields']['field_book_content']['field'] = 'field_book_content';
  $handler->display->display_options['fields']['field_book_content']['label'] = '';
  $handler->display->display_options['fields']['field_book_content']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_book_content']['element_default_classes'] = FALSE;
  /* Field: Content: MLID */
  $handler->display->display_options['fields']['field_book_mlid']['id'] = 'field_book_mlid';
  $handler->display->display_options['fields']['field_book_mlid']['table'] = 'field_data_field_book_mlid';
  $handler->display->display_options['fields']['field_book_mlid']['field'] = 'field_book_mlid';
  $handler->display->display_options['fields']['field_book_mlid']['label'] = '';
  $handler->display->display_options['fields']['field_book_mlid']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_book_mlid']['element_default_classes'] = FALSE;
  /* Field: Display */
  $handler->display->display_options['fields']['nothing']['id'] = 'nothing';
  $handler->display->display_options['fields']['nothing']['table'] = 'views';
  $handler->display->display_options['fields']['nothing']['field'] = 'nothing';
  $handler->display->display_options['fields']['nothing']['ui_name'] = 'Display';
  $handler->display->display_options['fields']['nothing']['label'] = '';
  $handler->display->display_options['fields']['nothing']['exclude'] = TRUE;
  $handler->display->display_options['fields']['nothing']['alter']['text'] = '<div class="shanti-texts-section">
<a name="shanti-texts-[nid]"></a>
<div id="shanti-texts-[nid]" class="shanti-texts-section-title text-level-[depth]">[title]</div>
<div class="shanti-texts-section-controls">
<a class="label label-default" href="/node/add/book?parent=[field_book_mlid]&field_og_collection_ref=[field_og_collection_ref_1]">Insert</a>
</div>
<div class="shanti-texts-section-content">
[field_book_content]
</div>
</div>';
  $handler->display->display_options['fields']['nothing']['element_label_colon'] = FALSE;
  /* Field: Content: Places */
  $handler->display->display_options['fields']['field_kmap_places']['id'] = 'field_kmap_places';
  $handler->display->display_options['fields']['field_kmap_places']['table'] = 'field_data_field_kmap_places';
  $handler->display->display_options['fields']['field_kmap_places']['field'] = 'field_kmap_places';
  $handler->display->display_options['fields']['field_kmap_places']['element_default_classes'] = FALSE;
  $handler->display->display_options['fields']['field_kmap_places']['click_sort_column'] = 'raw';
  $handler->display->display_options['fields']['field_kmap_places']['type'] = 'kmap_popover_formatter';
  $handler->display->display_options['fields']['field_kmap_places']['settings'] = array(
    'target' => '_blank',
  );
  $handler->display->display_options['fields']['field_kmap_places']['delta_offset'] = '0';
  $handler->display->display_options['fields']['field_kmap_places']['separator'] = ' ';
  /* Field: Content: Subjects */
  $handler->display->display_options['fields']['field_kmap_term']['id'] = 'field_kmap_term';
  $handler->display->display_options['fields']['field_kmap_term']['table'] = 'field_data_field_kmap_term';
  $handler->display->display_options['fields']['field_kmap_term']['field'] = 'field_kmap_term';
  $handler->display->display_options['fields']['field_kmap_term']['element_default_classes'] = FALSE;
  $handler->display->display_options['fields']['field_kmap_term']['click_sort_column'] = 'raw';
  $handler->display->display_options['fields']['field_kmap_term']['type'] = 'kmap_popover_formatter';
  $handler->display->display_options['fields']['field_kmap_term']['settings'] = array(
    'target' => '_blank',
  );
  $handler->display->display_options['fields']['field_kmap_term']['delta_offset'] = '0';
  $handler->display->display_options['fields']['field_kmap_term']['separator'] = ' ';
  /* Sort criterion: Book: Hierarchy */
  $handler->display->display_options['sorts']['p']['id'] = 'p';
  $handler->display->display_options['sorts']['p']['table'] = 'book_menu_links';
  $handler->display->display_options['sorts']['p']['field'] = 'p';
  $handler->display->display_options['sorts']['p']['sort_within_level'] = 0;
  /* Contextual filter: Content: Nid */
  $handler->display->display_options['arguments']['nid']['id'] = 'nid';
  $handler->display->display_options['arguments']['nid']['table'] = 'node';
  $handler->display->display_options['arguments']['nid']['field'] = 'nid';
  $handler->display->display_options['arguments']['nid']['relationship'] = 'bid';
  $handler->display->display_options['arguments']['nid']['default_action'] = 'default';
  $handler->display->display_options['arguments']['nid']['default_argument_type'] = 'node';
  $handler->display->display_options['arguments']['nid']['summary']['number_of_records'] = '0';
  $handler->display->display_options['arguments']['nid']['summary']['format'] = 'default_summary';
  $handler->display->display_options['arguments']['nid']['summary_options']['items_per_page'] = '25';
  /* Filter criterion: Content: Published */
  $handler->display->display_options['filters']['status']['id'] = 'status';
  $handler->display->display_options['filters']['status']['table'] = 'node';
  $handler->display->display_options['filters']['status']['field'] = 'status';
  $handler->display->display_options['filters']['status']['value'] = 1;
  $handler->display->display_options['filters']['status']['group'] = 1;
  $handler->display->display_options['filters']['status']['expose']['operator'] = FALSE;
  /* Filter criterion: Content: Type */
  $handler->display->display_options['filters']['type']['id'] = 'type';
  $handler->display->display_options['filters']['type']['table'] = 'node';
  $handler->display->display_options['filters']['type']['field'] = 'type';
  $handler->display->display_options['filters']['type']['value'] = array(
    'book' => 'book',
  );

  /* Display: Default */
  $handler = $view->new_display('panel_pane', 'Default', 'panel_pane_default');
  $handler->display->display_options['pane_category']['name'] = 'SHANTI Texts';
  $handler->display->display_options['pane_category']['weight'] = '0';
  $handler->display->display_options['argument_input'] = array(
    'nid' => array(
      'type' => 'context',
      'context' => 'entity:node.nid',
      'context_optional' => 0,
      'panel' => '0',
      'fixed' => '',
      'label' => 'Content: Nid',
    ),
  );
  $export['single_text_body'] = $view;

  $view = new view();
  $view->name = 'single_text_kmaps';
  $view->description = 'View of all the kmap terms associated with a text';
  $view->tag = 'SHANTI Texts';
  $view->base_table = 'node';
  $view->human_name = 'Single Text KMaps';
  $view->core = 7;
  $view->api_version = '3.0';
  $view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */

  /* Display: Master */
  $handler = $view->new_display('default', 'Master', 'default');
  $handler->display->display_options['use_more_always'] = FALSE;
  $handler->display->display_options['access']['type'] = 'perm';
  $handler->display->display_options['cache']['type'] = 'none';
  $handler->display->display_options['query']['type'] = 'views_query';
  $handler->display->display_options['exposed_form']['type'] = 'basic';
  $handler->display->display_options['pager']['type'] = 'full';
  $handler->display->display_options['style_plugin'] = 'default';
  $handler->display->display_options['style_options']['default_row_class'] = FALSE;
  $handler->display->display_options['style_options']['row_class_special'] = FALSE;
  $handler->display->display_options['row_plugin'] = 'fields';
  $handler->display->display_options['row_options']['default_field_elements'] = FALSE;
  /* Relationship: Book: Top level book */
  $handler->display->display_options['relationships']['bid']['id'] = 'bid';
  $handler->display->display_options['relationships']['bid']['table'] = 'book';
  $handler->display->display_options['relationships']['bid']['field'] = 'bid';
  $handler->display->display_options['relationships']['bid']['required'] = TRUE;
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'node';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['alter']['word_boundary'] = FALSE;
  $handler->display->display_options['fields']['title']['alter']['ellipsis'] = FALSE;
  $handler->display->display_options['fields']['title']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['title']['link_to_node'] = FALSE;
  /* Field: Content: Places */
  $handler->display->display_options['fields']['field_kmap_places']['id'] = 'field_kmap_places';
  $handler->display->display_options['fields']['field_kmap_places']['table'] = 'field_data_field_kmap_places';
  $handler->display->display_options['fields']['field_kmap_places']['field'] = 'field_kmap_places';
  $handler->display->display_options['fields']['field_kmap_places']['alter']['text'] = 'Places in [title]: [field_kmap_places] ';
  $handler->display->display_options['fields']['field_kmap_places']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_kmap_places']['hide_empty'] = TRUE;
  $handler->display->display_options['fields']['field_kmap_places']['click_sort_column'] = 'raw';
  $handler->display->display_options['fields']['field_kmap_places']['type'] = 'kmap_popover_formatter';
  $handler->display->display_options['fields']['field_kmap_places']['settings'] = array(
    'target' => '_blank',
  );
  $handler->display->display_options['fields']['field_kmap_places']['delta_offset'] = '0';
  $handler->display->display_options['fields']['field_kmap_places']['multi_type'] = 'ul';
  /* Field: Content: Subjects */
  $handler->display->display_options['fields']['field_kmap_term']['id'] = 'field_kmap_term';
  $handler->display->display_options['fields']['field_kmap_term']['table'] = 'field_data_field_kmap_term';
  $handler->display->display_options['fields']['field_kmap_term']['field'] = 'field_kmap_term';
  $handler->display->display_options['fields']['field_kmap_term']['alter']['text'] = 'Subjects in [title]: [field_kmap_term]';
  $handler->display->display_options['fields']['field_kmap_term']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_kmap_term']['hide_empty'] = TRUE;
  $handler->display->display_options['fields']['field_kmap_term']['click_sort_column'] = 'raw';
  $handler->display->display_options['fields']['field_kmap_term']['type'] = 'kmap_popover_formatter';
  $handler->display->display_options['fields']['field_kmap_term']['settings'] = array(
    'target' => '_blank',
  );
  $handler->display->display_options['fields']['field_kmap_term']['delta_offset'] = '0';
  $handler->display->display_options['fields']['field_kmap_term']['multi_type'] = 'ul';
  /* Contextual filter: Content: Nid */
  $handler->display->display_options['arguments']['nid']['id'] = 'nid';
  $handler->display->display_options['arguments']['nid']['table'] = 'node';
  $handler->display->display_options['arguments']['nid']['field'] = 'nid';
  $handler->display->display_options['arguments']['nid']['relationship'] = 'bid';
  $handler->display->display_options['arguments']['nid']['default_action'] = 'default';
  $handler->display->display_options['arguments']['nid']['default_argument_type'] = 'node';
  $handler->display->display_options['arguments']['nid']['summary']['number_of_records'] = '0';
  $handler->display->display_options['arguments']['nid']['summary']['format'] = 'default_summary';
  $handler->display->display_options['arguments']['nid']['summary_options']['items_per_page'] = '25';
  /* Filter criterion: Content: Published */
  $handler->display->display_options['filters']['status']['id'] = 'status';
  $handler->display->display_options['filters']['status']['table'] = 'node';
  $handler->display->display_options['filters']['status']['field'] = 'status';
  $handler->display->display_options['filters']['status']['value'] = 1;
  $handler->display->display_options['filters']['status']['group'] = 1;
  $handler->display->display_options['filters']['status']['expose']['operator'] = FALSE;
  /* Filter criterion: Content: Type */
  $handler->display->display_options['filters']['type']['id'] = 'type';
  $handler->display->display_options['filters']['type']['table'] = 'node';
  $handler->display->display_options['filters']['type']['field'] = 'type';
  $handler->display->display_options['filters']['type']['value'] = array(
    'book' => 'book',
  );

  /* Display: Default */
  $handler = $view->new_display('panel_pane', 'Default', 'panel_pane_default');
  $export['single_text_kmaps'] = $view;

  $view = new view();
  $view->name = 'single_text_meta';
  $view->description = '';
  $view->tag = 'SHANTI Texts';
  $view->base_table = 'node';
  $view->human_name = 'Single Text Meta';
  $view->core = 7;
  $view->api_version = '3.0';
  $view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */

  /* Display: Master */
  $handler = $view->new_display('default', 'Master', 'default');
  $handler->display->display_options['use_more_always'] = FALSE;
  $handler->display->display_options['access']['type'] = 'perm';
  $handler->display->display_options['cache']['type'] = 'none';
  $handler->display->display_options['query']['type'] = 'views_query';
  $handler->display->display_options['query']['options']['distinct'] = TRUE;
  $handler->display->display_options['exposed_form']['type'] = 'basic';
  $handler->display->display_options['pager']['type'] = 'some';
  $handler->display->display_options['pager']['options']['items_per_page'] = '1';
  $handler->display->display_options['pager']['options']['offset'] = '0';
  $handler->display->display_options['style_plugin'] = 'default';
  $handler->display->display_options['style_options']['default_row_class'] = FALSE;
  $handler->display->display_options['style_options']['row_class_special'] = FALSE;
  $handler->display->display_options['row_plugin'] = 'fields';
  $handler->display->display_options['row_options']['default_field_elements'] = FALSE;
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'node';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['exclude'] = TRUE;
  $handler->display->display_options['fields']['title']['alter']['word_boundary'] = FALSE;
  $handler->display->display_options['fields']['title']['alter']['ellipsis'] = FALSE;
  $handler->display->display_options['fields']['title']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['title']['hide_empty'] = TRUE;
  $handler->display->display_options['fields']['title']['link_to_node'] = FALSE;
  /* Field: Content: Description */
  $handler->display->display_options['fields']['field_dc_description']['id'] = 'field_dc_description';
  $handler->display->display_options['fields']['field_dc_description']['table'] = 'field_data_field_dc_description';
  $handler->display->display_options['fields']['field_dc_description']['field'] = 'field_dc_description';
  $handler->display->display_options['fields']['field_dc_description']['label'] = '';
  $handler->display->display_options['fields']['field_dc_description']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_dc_description']['hide_empty'] = TRUE;
  /* Field: Content: Author */
  $handler->display->display_options['fields']['field_book_author']['id'] = 'field_book_author';
  $handler->display->display_options['fields']['field_book_author']['table'] = 'field_data_field_book_author';
  $handler->display->display_options['fields']['field_book_author']['field'] = 'field_book_author';
  $handler->display->display_options['fields']['field_book_author']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_book_author']['hide_empty'] = TRUE;
  $handler->display->display_options['fields']['field_book_author']['delta_offset'] = '0';
  /* Field: Content: Editor */
  $handler->display->display_options['fields']['field_book_editor']['id'] = 'field_book_editor';
  $handler->display->display_options['fields']['field_book_editor']['table'] = 'field_data_field_book_editor';
  $handler->display->display_options['fields']['field_book_editor']['field'] = 'field_book_editor';
  $handler->display->display_options['fields']['field_book_editor']['alter']['text'] = '<tr><td>Editor</td><td>[field_book_editor] </td></tr>';
  $handler->display->display_options['fields']['field_book_editor']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_book_editor']['hide_empty'] = TRUE;
  /* Field: Content: Translator */
  $handler->display->display_options['fields']['field_book_translator']['id'] = 'field_book_translator';
  $handler->display->display_options['fields']['field_book_translator']['table'] = 'field_data_field_book_translator';
  $handler->display->display_options['fields']['field_book_translator']['field'] = 'field_book_translator';
  $handler->display->display_options['fields']['field_book_translator']['alter']['text'] = '<tr><td>Translator</td><td>[field_book_translator] </td></tr>';
  $handler->display->display_options['fields']['field_book_translator']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_book_translator']['hide_empty'] = TRUE;
  /* Field: Content: Publication year */
  $handler->display->display_options['fields']['field_dc_date_publication_year']['id'] = 'field_dc_date_publication_year';
  $handler->display->display_options['fields']['field_dc_date_publication_year']['table'] = 'field_data_field_dc_date_publication_year';
  $handler->display->display_options['fields']['field_dc_date_publication_year']['field'] = 'field_dc_date_publication_year';
  $handler->display->display_options['fields']['field_dc_date_publication_year']['label'] = 'Year published';
  $handler->display->display_options['fields']['field_dc_date_publication_year']['alter']['text'] = '<tr><td>Year</td><td>[field_dc_date_publication_year]</td></tr>';
  $handler->display->display_options['fields']['field_dc_date_publication_year']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_dc_date_publication_year']['hide_empty'] = TRUE;
  $handler->display->display_options['fields']['field_dc_date_publication_year']['settings'] = array(
    'format_type' => 'year_only',
    'fromto' => 'both',
    'multiple_number' => '',
    'multiple_from' => '',
    'multiple_to' => '',
  );
  /* Field: Content: Original publication year */
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['id'] = 'field_dc_date_orginial_year';
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['table'] = 'field_data_field_dc_date_orginial_year';
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['field'] = 'field_dc_date_orginial_year';
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['label'] = 'Original year published';
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['alter']['text'] = '<tr><td>Year</td><td>[field_dc_date_publication_year] [field_dc_date_orginial_year]</td></tr>';
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['hide_empty'] = TRUE;
  $handler->display->display_options['fields']['field_dc_date_orginial_year']['settings'] = array(
    'format_type' => 'year_only',
    'fromto' => 'both',
    'multiple_number' => '',
    'multiple_from' => '',
    'multiple_to' => '',
  );
  /* Field: Content: Subjects */
  $handler->display->display_options['fields']['field_kmap_term']['id'] = 'field_kmap_term';
  $handler->display->display_options['fields']['field_kmap_term']['table'] = 'field_data_field_kmap_term';
  $handler->display->display_options['fields']['field_kmap_term']['field'] = 'field_kmap_term';
  $handler->display->display_options['fields']['field_kmap_term']['alter']['text'] = '<tr><td>Subjects</td><td>[field_kmap_term]</td></tr>';
  $handler->display->display_options['fields']['field_kmap_term']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_kmap_term']['hide_empty'] = TRUE;
  $handler->display->display_options['fields']['field_kmap_term']['click_sort_column'] = 'raw';
  $handler->display->display_options['fields']['field_kmap_term']['type'] = 'kmap_popover_formatter';
  $handler->display->display_options['fields']['field_kmap_term']['settings'] = array(
    'target' => '_blank',
  );
  $handler->display->display_options['fields']['field_kmap_term']['delta_offset'] = '0';
  $handler->display->display_options['fields']['field_kmap_term']['multi_type'] = 'ul';
  $handler->display->display_options['fields']['field_kmap_term']['separator'] = '';
  /* Field: Content: Places */
  $handler->display->display_options['fields']['field_kmap_places']['id'] = 'field_kmap_places';
  $handler->display->display_options['fields']['field_kmap_places']['table'] = 'field_data_field_kmap_places';
  $handler->display->display_options['fields']['field_kmap_places']['field'] = 'field_kmap_places';
  $handler->display->display_options['fields']['field_kmap_places']['alter']['text'] = '<tr>
<td>Places</td>
<td>[field_kmap_places]</td>
</tr>';
  $handler->display->display_options['fields']['field_kmap_places']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_kmap_places']['hide_empty'] = TRUE;
  $handler->display->display_options['fields']['field_kmap_places']['click_sort_column'] = 'raw';
  $handler->display->display_options['fields']['field_kmap_places']['type'] = 'kmap_popover_formatter';
  $handler->display->display_options['fields']['field_kmap_places']['settings'] = array(
    'target' => '_blank',
  );
  $handler->display->display_options['fields']['field_kmap_places']['delta_offset'] = '0';
  $handler->display->display_options['fields']['field_kmap_places']['multi_type'] = 'ul';
  $handler->display->display_options['fields']['field_kmap_places']['separator'] = ' ';
  /* Field: Content: Rights */
  $handler->display->display_options['fields']['field_dc_rights_general']['id'] = 'field_dc_rights_general';
  $handler->display->display_options['fields']['field_dc_rights_general']['table'] = 'field_data_field_dc_rights_general';
  $handler->display->display_options['fields']['field_dc_rights_general']['field'] = 'field_dc_rights_general';
  $handler->display->display_options['fields']['field_dc_rights_general']['alter']['text'] = '<tr>
<td>Rights</td>
<td>[field_dc_rights_general]</td>
</tr>';
  $handler->display->display_options['fields']['field_dc_rights_general']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_dc_rights_general']['hide_empty'] = TRUE;
  /* Field: Content: Rights (CC) */
  $handler->display->display_options['fields']['field_dc_rights_creativecommons']['id'] = 'field_dc_rights_creativecommons';
  $handler->display->display_options['fields']['field_dc_rights_creativecommons']['table'] = 'field_data_field_dc_rights_creativecommons';
  $handler->display->display_options['fields']['field_dc_rights_creativecommons']['field'] = 'field_dc_rights_creativecommons';
  $handler->display->display_options['fields']['field_dc_rights_creativecommons']['label'] = '';
  $handler->display->display_options['fields']['field_dc_rights_creativecommons']['alter']['text'] = '<tr>
<td colspan="2">[field_dc_rights_general]</td>
</tr>';
  $handler->display->display_options['fields']['field_dc_rights_creativecommons']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['field_dc_rights_creativecommons']['hide_empty'] = TRUE;
  /* Field: Global: Custom text */
  $handler->display->display_options['fields']['nothing']['id'] = 'nothing';
  $handler->display->display_options['fields']['nothing']['table'] = 'views';
  $handler->display->display_options['fields']['nothing']['field'] = 'nothing';
  $handler->display->display_options['fields']['nothing']['label'] = '';
  $handler->display->display_options['fields']['nothing']['exclude'] = TRUE;
  $handler->display->display_options['fields']['nothing']['alter']['text'] = '[title]
[field_dc_description]
<table class="table">
[field_book_author]
[field_book_editor]
[field_book_translator]
[field_dc_date_publication_year]
[field_dc_date_orginial_year]
[field_kmap_term]
[field_kmap_places]
[field_dc_rights_general]
[field_dc_rights_creativecommons]
</table>
';
  $handler->display->display_options['fields']['nothing']['element_label_colon'] = FALSE;
  /* Contextual filter: Content: Nid */
  $handler->display->display_options['arguments']['nid']['id'] = 'nid';
  $handler->display->display_options['arguments']['nid']['table'] = 'node';
  $handler->display->display_options['arguments']['nid']['field'] = 'nid';
  $handler->display->display_options['arguments']['nid']['default_action'] = 'default';
  $handler->display->display_options['arguments']['nid']['default_argument_type'] = 'node';
  $handler->display->display_options['arguments']['nid']['summary']['number_of_records'] = '0';
  $handler->display->display_options['arguments']['nid']['summary']['format'] = 'default_summary';
  $handler->display->display_options['arguments']['nid']['summary_options']['items_per_page'] = '25';
  /* Filter criterion: Content: Published */
  $handler->display->display_options['filters']['status']['id'] = 'status';
  $handler->display->display_options['filters']['status']['table'] = 'node';
  $handler->display->display_options['filters']['status']['field'] = 'status';
  $handler->display->display_options['filters']['status']['value'] = 1;
  $handler->display->display_options['filters']['status']['group'] = 1;
  $handler->display->display_options['filters']['status']['expose']['operator'] = FALSE;
  /* Filter criterion: Content: Type */
  $handler->display->display_options['filters']['type']['id'] = 'type';
  $handler->display->display_options['filters']['type']['table'] = 'node';
  $handler->display->display_options['filters']['type']['field'] = 'type';
  $handler->display->display_options['filters']['type']['value'] = array(
    'book' => 'book',
  );

  /* Display: Default */
  $handler = $view->new_display('panel_pane', 'Default', 'panel_pane_default');
  $handler->display->display_options['pane_category']['name'] = 'SHANTI Texts';
  $handler->display->display_options['pane_category']['weight'] = '0';
  $export['single_text_meta'] = $view;

  $view = new view();
  $view->name = 'single_text_toc';
  $view->description = '';
  $view->tag = 'SHANTI Texts';
  $view->base_table = 'node';
  $view->human_name = 'Single Text TOC';
  $view->core = 7;
  $view->api_version = '3.0';
  $view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */

  /* Display: Master */
  $handler = $view->new_display('default', 'Master', 'default');
  $handler->display->display_options['title'] = 'Text TOC';
  $handler->display->display_options['use_more_always'] = FALSE;
  $handler->display->display_options['access']['type'] = 'perm';
  $handler->display->display_options['cache']['type'] = 'none';
  $handler->display->display_options['query']['type'] = 'views_query';
  $handler->display->display_options['exposed_form']['type'] = 'basic';
  $handler->display->display_options['pager']['type'] = 'none';
  $handler->display->display_options['pager']['options']['offset'] = '0';
  $handler->display->display_options['style_plugin'] = 'tree';
  $handler->display->display_options['style_options']['main_field'] = 'nid';
  $handler->display->display_options['style_options']['parent_field'] = 'nid_1';
  $handler->display->display_options['row_plugin'] = 'fields';
  $handler->display->display_options['row_options']['inline'] = array(
    'title' => 'title',
  );
  $handler->display->display_options['row_options']['default_field_elements'] = FALSE;
  /* Relationship: Book: Parent */
  $handler->display->display_options['relationships']['nid']['id'] = 'nid';
  $handler->display->display_options['relationships']['nid']['table'] = 'book_parent';
  $handler->display->display_options['relationships']['nid']['field'] = 'nid';
  /* Relationship: Book: Top level book */
  $handler->display->display_options['relationships']['bid']['id'] = 'bid';
  $handler->display->display_options['relationships']['bid']['table'] = 'book';
  $handler->display->display_options['relationships']['bid']['field'] = 'bid';
  /* Field: Content: Nid */
  $handler->display->display_options['fields']['nid']['id'] = 'nid';
  $handler->display->display_options['fields']['nid']['table'] = 'node';
  $handler->display->display_options['fields']['nid']['field'] = 'nid';
  $handler->display->display_options['fields']['nid']['label'] = '';
  $handler->display->display_options['fields']['nid']['exclude'] = TRUE;
  $handler->display->display_options['fields']['nid']['element_label_colon'] = FALSE;
  /* Field: Parent ID */
  $handler->display->display_options['fields']['nid_1']['id'] = 'nid_1';
  $handler->display->display_options['fields']['nid_1']['table'] = 'node';
  $handler->display->display_options['fields']['nid_1']['field'] = 'nid';
  $handler->display->display_options['fields']['nid_1']['relationship'] = 'nid';
  $handler->display->display_options['fields']['nid_1']['ui_name'] = 'Parent ID';
  $handler->display->display_options['fields']['nid_1']['label'] = '';
  $handler->display->display_options['fields']['nid_1']['exclude'] = TRUE;
  $handler->display->display_options['fields']['nid_1']['element_label_colon'] = FALSE;
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'node';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['alter']['make_link'] = TRUE;
  $handler->display->display_options['fields']['title']['alter']['path'] = '#shanti-texts-[nid]';
  $handler->display->display_options['fields']['title']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['title']['link_to_node'] = FALSE;
  /* Contextual filter: Content: Nid */
  $handler->display->display_options['arguments']['nid']['id'] = 'nid';
  $handler->display->display_options['arguments']['nid']['table'] = 'node';
  $handler->display->display_options['arguments']['nid']['field'] = 'nid';
  $handler->display->display_options['arguments']['nid']['relationship'] = 'bid';
  $handler->display->display_options['arguments']['nid']['default_action'] = 'default';
  $handler->display->display_options['arguments']['nid']['default_argument_type'] = 'node';
  $handler->display->display_options['arguments']['nid']['summary']['number_of_records'] = '0';
  $handler->display->display_options['arguments']['nid']['summary']['format'] = 'default_summary';
  $handler->display->display_options['arguments']['nid']['summary_options']['items_per_page'] = '25';
  /* Filter criterion: Content: Published */
  $handler->display->display_options['filters']['status']['id'] = 'status';
  $handler->display->display_options['filters']['status']['table'] = 'node';
  $handler->display->display_options['filters']['status']['field'] = 'status';
  $handler->display->display_options['filters']['status']['value'] = 1;
  $handler->display->display_options['filters']['status']['group'] = 1;
  $handler->display->display_options['filters']['status']['expose']['operator'] = FALSE;
  /* Filter criterion: Content: Type */
  $handler->display->display_options['filters']['type']['id'] = 'type';
  $handler->display->display_options['filters']['type']['table'] = 'node';
  $handler->display->display_options['filters']['type']['field'] = 'type';
  $handler->display->display_options['filters']['type']['value'] = array(
    'book' => 'book',
  );
  /* Filter criterion: Book: Depth */
  $handler->display->display_options['filters']['depth']['id'] = 'depth';
  $handler->display->display_options['filters']['depth']['table'] = 'book_menu_links';
  $handler->display->display_options['filters']['depth']['field'] = 'depth';
  $handler->display->display_options['filters']['depth']['operator'] = '>';
  $handler->display->display_options['filters']['depth']['value']['value'] = '1';

  /* Display: Default */
  $handler = $view->new_display('panel_pane', 'Default', 'panel_pane_default');
  $handler->display->display_options['pane_title'] = 'Text TOC';
  $handler->display->display_options['pane_description'] = 'Use in a panel or template for viewing combined texts.';
  $handler->display->display_options['pane_category']['name'] = 'SHANTI Texts';
  $handler->display->display_options['pane_category']['weight'] = '0';
  $handler->display->display_options['allow']['use_pager'] = 0;
  $handler->display->display_options['allow']['items_per_page'] = 0;
  $handler->display->display_options['allow']['offset'] = 0;
  $handler->display->display_options['allow']['link_to_view'] = 0;
  $handler->display->display_options['allow']['more_link'] = 0;
  $handler->display->display_options['allow']['path_override'] = 0;
  $handler->display->display_options['allow']['title_override'] = 'title_override';
  $handler->display->display_options['allow']['exposed_form'] = 0;
  $handler->display->display_options['allow']['fields_override'] = 0;
  $export['single_text_toc'] = $view;

  $view = new view();
  $view->name = 'single_text_views';
  $view->description = '';
  $view->tag = 'SHANTI Texts';
  $view->base_table = 'node';
  $view->human_name = 'Single Text Views';
  $view->core = 7;
  $view->api_version = '3.0';
  $view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */

  /* Display: Master */
  $handler = $view->new_display('default', 'Master', 'default');
  $handler->display->display_options['use_more_always'] = FALSE;
  $handler->display->display_options['access']['type'] = 'perm';
  $handler->display->display_options['cache']['type'] = 'none';
  $handler->display->display_options['query']['type'] = 'views_query';
  $handler->display->display_options['exposed_form']['type'] = 'basic';
  $handler->display->display_options['pager']['type'] = 'full';
  $handler->display->display_options['style_plugin'] = 'default';
  $handler->display->display_options['style_options']['default_row_class'] = FALSE;
  $handler->display->display_options['style_options']['row_class_special'] = FALSE;
  $handler->display->display_options['row_plugin'] = 'fields';
  $handler->display->display_options['row_options']['default_field_elements'] = FALSE;
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'node';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['exclude'] = TRUE;
  $handler->display->display_options['fields']['title']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['title']['link_to_node'] = FALSE;
  /* Field: Content: Nid */
  $handler->display->display_options['fields']['nid']['id'] = 'nid';
  $handler->display->display_options['fields']['nid']['table'] = 'node';
  $handler->display->display_options['fields']['nid']['field'] = 'nid';
  $handler->display->display_options['fields']['nid']['label'] = '';
  $handler->display->display_options['fields']['nid']['exclude'] = TRUE;
  $handler->display->display_options['fields']['nid']['element_label_colon'] = FALSE;
  /* Field: PubReader Link */
  $handler->display->display_options['fields']['nothing']['id'] = 'nothing';
  $handler->display->display_options['fields']['nothing']['table'] = 'views';
  $handler->display->display_options['fields']['nothing']['field'] = 'nothing';
  $handler->display->display_options['fields']['nothing']['ui_name'] = 'PubReader Link';
  $handler->display->display_options['fields']['nothing']['label'] = '';
  $handler->display->display_options['fields']['nothing']['alter']['text'] = 'View in PubReader';
  $handler->display->display_options['fields']['nothing']['alter']['make_link'] = TRUE;
  $handler->display->display_options['fields']['nothing']['alter']['path'] = 'book_pubreader/[nid]';
  $handler->display->display_options['fields']['nothing']['alter']['alt'] = 'View book in NIH PubReader';
  $handler->display->display_options['fields']['nothing']['alter']['target'] = '_blank';
  $handler->display->display_options['fields']['nothing']['element_label_colon'] = FALSE;
  /* Field: Voyant Link */
  $handler->display->display_options['fields']['nothing_1']['id'] = 'nothing_1';
  $handler->display->display_options['fields']['nothing_1']['table'] = 'views';
  $handler->display->display_options['fields']['nothing_1']['field'] = 'nothing';
  $handler->display->display_options['fields']['nothing_1']['ui_name'] = 'Voyant Link';
  $handler->display->display_options['fields']['nothing_1']['label'] = '';
  $handler->display->display_options['fields']['nothing_1']['alter']['text'] = 'View in Voyant';
  $handler->display->display_options['fields']['nothing_1']['alter']['make_link'] = TRUE;
  $handler->display->display_options['fields']['nothing_1']['alter']['path'] = 'shanti_texts/voyant/[nid]';
  $handler->display->display_options['fields']['nothing_1']['alter']['alt'] = 'View book in Voyant tools';
  $handler->display->display_options['fields']['nothing_1']['alter']['target'] = '_blank';
  $handler->display->display_options['fields']['nothing_1']['element_label_colon'] = FALSE;
  /* Field: Display */
  $handler->display->display_options['fields']['nothing_2']['id'] = 'nothing_2';
  $handler->display->display_options['fields']['nothing_2']['table'] = 'views';
  $handler->display->display_options['fields']['nothing_2']['field'] = 'nothing';
  $handler->display->display_options['fields']['nothing_2']['ui_name'] = 'Display';
  $handler->display->display_options['fields']['nothing_2']['label'] = '';
  $handler->display->display_options['fields']['nothing_2']['exclude'] = TRUE;
  $handler->display->display_options['fields']['nothing_2']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['nothing_2']['element_default_classes'] = FALSE;
  /* Contextual filter: Content: Nid */
  $handler->display->display_options['arguments']['nid']['id'] = 'nid';
  $handler->display->display_options['arguments']['nid']['table'] = 'node';
  $handler->display->display_options['arguments']['nid']['field'] = 'nid';
  $handler->display->display_options['arguments']['nid']['default_action'] = 'default';
  $handler->display->display_options['arguments']['nid']['default_argument_type'] = 'node';
  $handler->display->display_options['arguments']['nid']['summary']['number_of_records'] = '0';
  $handler->display->display_options['arguments']['nid']['summary']['format'] = 'default_summary';
  $handler->display->display_options['arguments']['nid']['summary_options']['items_per_page'] = '25';
  /* Filter criterion: Content: Published */
  $handler->display->display_options['filters']['status']['id'] = 'status';
  $handler->display->display_options['filters']['status']['table'] = 'node';
  $handler->display->display_options['filters']['status']['field'] = 'status';
  $handler->display->display_options['filters']['status']['value'] = 1;
  $handler->display->display_options['filters']['status']['group'] = 1;
  $handler->display->display_options['filters']['status']['expose']['operator'] = FALSE;
  /* Filter criterion: Content: Type */
  $handler->display->display_options['filters']['type']['id'] = 'type';
  $handler->display->display_options['filters']['type']['table'] = 'node';
  $handler->display->display_options['filters']['type']['field'] = 'type';
  $handler->display->display_options['filters']['type']['value'] = array(
    'book' => 'book',
  );

  /* Display: Default */
  $handler = $view->new_display('panel_pane', 'Default', 'panel_pane_default');
  $handler->display->display_options['pane_category']['name'] = 'SHANTI Texts';
  $handler->display->display_options['pane_category']['weight'] = '0';
  $export['single_text_views'] = $view;

  $view = new view();
  $view->name = 'text_search';
  $view->description = '';
  $view->tag = 'default';
  $view->base_table = 'node';
  $view->human_name = 'Text Search';
  $view->core = 7;
  $view->api_version = '3.0';
  $view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */

  /* Display: Master */
  $handler = $view->new_display('default', 'Master', 'default');
  $handler->display->display_options['title'] = 'Text Search';
  $handler->display->display_options['display_description'] = 'Full Text Search';
  $handler->display->display_options['use_ajax'] = TRUE;
  $handler->display->display_options['hide_admin_links'] = TRUE;
  $handler->display->display_options['use_more_always'] = FALSE;
  $handler->display->display_options['access']['type'] = 'perm';
  $handler->display->display_options['cache']['type'] = 'none';
  $handler->display->display_options['query']['type'] = 'views_query';
  $handler->display->display_options['exposed_form']['type'] = 'basic';
  $handler->display->display_options['exposed_form']['options']['submit_button'] = '&#8203;';
  $handler->display->display_options['exposed_form']['options']['reset_button'] = TRUE;
  $handler->display->display_options['exposed_form']['options']['expose_sort_order'] = FALSE;
  $handler->display->display_options['pager']['type'] = 'pagerer';
  $handler->display->display_options['pager']['options']['items_per_page'] = '20';
  $handler->display->display_options['pager']['options']['offset'] = '0';
  $handler->display->display_options['pager']['options']['id'] = '0';
  $handler->display->display_options['pager']['options']['quantity'] = '9';
  $handler->display->display_options['pager']['options']['preset'] = 'shanti_default';
  $handler->display->display_options['style_plugin'] = 'default';
  $handler->display->display_options['style_options']['grouping'] = array(
    0 => array(
      'field' => 'title_1',
      'rendered' => 0,
      'rendered_strip' => 0,
    ),
  );
  $handler->display->display_options['style_options']['default_row_class'] = FALSE;
  $handler->display->display_options['style_options']['row_class_special'] = FALSE;
  $handler->display->display_options['row_plugin'] = 'fields';
  $handler->display->display_options['row_options']['default_field_elements'] = FALSE;
  /* No results behavior: Global: Text area */
  $handler->display->display_options['empty']['area']['id'] = 'area';
  $handler->display->display_options['empty']['area']['table'] = 'views';
  $handler->display->display_options['empty']['area']['field'] = 'area';
  $handler->display->display_options['empty']['area']['empty'] = TRUE;
  $handler->display->display_options['empty']['area']['content'] = 'Sorry, there were no results for your search string.';
  $handler->display->display_options['empty']['area']['format'] = 'plain_text';
  /* Relationship: Book: Top level book */
  $handler->display->display_options['relationships']['bid']['id'] = 'bid';
  $handler->display->display_options['relationships']['bid']['table'] = 'book';
  $handler->display->display_options['relationships']['bid']['field'] = 'bid';
  $handler->display->display_options['relationships']['bid']['label'] = 'Parent';
  $handler->display->display_options['relationships']['bid']['required'] = TRUE;
  /* Field: Book: Depth */
  $handler->display->display_options['fields']['depth']['id'] = 'depth';
  $handler->display->display_options['fields']['depth']['table'] = 'book_menu_links';
  $handler->display->display_options['fields']['depth']['field'] = 'depth';
  $handler->display->display_options['fields']['depth']['label'] = '';
  $handler->display->display_options['fields']['depth']['exclude'] = TRUE;
  $handler->display->display_options['fields']['depth']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['depth']['separator'] = '';
  /* Field: Book: Weight */
  $handler->display->display_options['fields']['weight']['id'] = 'weight';
  $handler->display->display_options['fields']['weight']['table'] = 'book_menu_links';
  $handler->display->display_options['fields']['weight']['field'] = 'weight';
  $handler->display->display_options['fields']['weight']['label'] = '';
  $handler->display->display_options['fields']['weight']['exclude'] = TRUE;
  $handler->display->display_options['fields']['weight']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['weight']['separator'] = '';
  /* Field: Content: Nid */
  $handler->display->display_options['fields']['nid_1']['id'] = 'nid_1';
  $handler->display->display_options['fields']['nid_1']['table'] = 'node';
  $handler->display->display_options['fields']['nid_1']['field'] = 'nid';
  $handler->display->display_options['fields']['nid_1']['label'] = '';
  $handler->display->display_options['fields']['nid_1']['exclude'] = TRUE;
  $handler->display->display_options['fields']['nid_1']['element_label_colon'] = FALSE;
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title_1']['id'] = 'title_1';
  $handler->display->display_options['fields']['title_1']['table'] = 'node';
  $handler->display->display_options['fields']['title_1']['field'] = 'title';
  $handler->display->display_options['fields']['title_1']['relationship'] = 'bid';
  $handler->display->display_options['fields']['title_1']['label'] = '';
  $handler->display->display_options['fields']['title_1']['exclude'] = TRUE;
  $handler->display->display_options['fields']['title_1']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['title_1']['element_default_classes'] = FALSE;
  /* Field: Content: Nid */
  $handler->display->display_options['fields']['nid']['id'] = 'nid';
  $handler->display->display_options['fields']['nid']['table'] = 'node';
  $handler->display->display_options['fields']['nid']['field'] = 'nid';
  $handler->display->display_options['fields']['nid']['relationship'] = 'bid';
  $handler->display->display_options['fields']['nid']['label'] = '';
  $handler->display->display_options['fields']['nid']['exclude'] = TRUE;
  $handler->display->display_options['fields']['nid']['alter']['text'] = '[title_1]';
  $handler->display->display_options['fields']['nid']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['nid']['element_default_classes'] = FALSE;
  /* Field: Content: Title */
  $handler->display->display_options['fields']['title']['id'] = 'title';
  $handler->display->display_options['fields']['title']['table'] = 'node';
  $handler->display->display_options['fields']['title']['field'] = 'title';
  $handler->display->display_options['fields']['title']['label'] = '';
  $handler->display->display_options['fields']['title']['exclude'] = TRUE;
  $handler->display->display_options['fields']['title']['alter']['alter_text'] = TRUE;
  $handler->display->display_options['fields']['title']['alter']['text'] = '<li class="mega-search-title depth-[depth] weight-[weight]">[title]</li>';
  $handler->display->display_options['fields']['title']['alter']['word_boundary'] = FALSE;
  $handler->display->display_options['fields']['title']['alter']['ellipsis'] = FALSE;
  $handler->display->display_options['fields']['title']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['title']['element_default_classes'] = FALSE;
  /* Field: Global: PHP */
  $handler->display->display_options['fields']['php']['id'] = 'php';
  $handler->display->display_options['fields']['php']['table'] = 'views';
  $handler->display->display_options['fields']['php']['field'] = 'php';
  $handler->display->display_options['fields']['php']['label'] = '';
  $handler->display->display_options['fields']['php']['element_label_colon'] = FALSE;
  $handler->display->display_options['fields']['php']['use_php_setup'] = 0;
  $handler->display->display_options['fields']['php']['php_output'] = '<?php 
if ($row->nid != $row->nid_1) {
echo "<div class=\'mega-search-title depth-{$row->depth} weight-{$row->weight}\'><a href=\'/node/{$row->nid_1}\'>{$row->title}</a></div>"; 
}
?>';
  $handler->display->display_options['fields']['php']['use_php_click_sortable'] = '0';
  $handler->display->display_options['fields']['php']['php_click_sortable'] = '';
  /* Sort criterion: Content: Title */
  $handler->display->display_options['sorts']['title']['id'] = 'title';
  $handler->display->display_options['sorts']['title']['table'] = 'node';
  $handler->display->display_options['sorts']['title']['field'] = 'title';
  $handler->display->display_options['sorts']['title']['relationship'] = 'bid';
  /* Sort criterion: Content: Nid */
  $handler->display->display_options['sorts']['nid']['id'] = 'nid';
  $handler->display->display_options['sorts']['nid']['table'] = 'node';
  $handler->display->display_options['sorts']['nid']['field'] = 'nid';
  $handler->display->display_options['sorts']['nid']['relationship'] = 'bid';
  /* Sort criterion: Book: Hierarchy */
  $handler->display->display_options['sorts']['p']['id'] = 'p';
  $handler->display->display_options['sorts']['p']['table'] = 'book_menu_links';
  $handler->display->display_options['sorts']['p']['field'] = 'p';
  $handler->display->display_options['sorts']['p']['sort_within_level'] = 0;
  /* Filter criterion: Content: Published */
  $handler->display->display_options['filters']['status']['id'] = 'status';
  $handler->display->display_options['filters']['status']['table'] = 'node';
  $handler->display->display_options['filters']['status']['field'] = 'status';
  $handler->display->display_options['filters']['status']['value'] = 1;
  $handler->display->display_options['filters']['status']['group'] = 1;
  $handler->display->display_options['filters']['status']['expose']['operator'] = FALSE;
  /* Filter criterion: Content: Type */
  $handler->display->display_options['filters']['type']['id'] = 'type';
  $handler->display->display_options['filters']['type']['table'] = 'node';
  $handler->display->display_options['filters']['type']['field'] = 'type';
  $handler->display->display_options['filters']['type']['value'] = array(
    'book' => 'book',
  );
  $handler->display->display_options['filters']['type']['group'] = 1;
  $handler->display->display_options['filters']['type']['expose']['operator_id'] = 'type_op';
  $handler->display->display_options['filters']['type']['expose']['label'] = 'Type';
  $handler->display->display_options['filters']['type']['expose']['operator'] = 'type_op';
  $handler->display->display_options['filters']['type']['expose']['identifier'] = 'type';
  /* Filter criterion: Book: Depth */
  $handler->display->display_options['filters']['depth']['id'] = 'depth';
  $handler->display->display_options['filters']['depth']['table'] = 'book_menu_links';
  $handler->display->display_options['filters']['depth']['field'] = 'depth';
  $handler->display->display_options['filters']['depth']['operator'] = '>';
  $handler->display->display_options['filters']['depth']['value']['value'] = '1';

  /* Display: Default */
  $handler = $view->new_display('block', 'Default', 'block_1');
  $handler->display->display_options['defaults']['arguments'] = FALSE;
  /* Contextual filter: Content: Author uid */
  $handler->display->display_options['arguments']['uid']['id'] = 'uid';
  $handler->display->display_options['arguments']['uid']['table'] = 'node';
  $handler->display->display_options['arguments']['uid']['field'] = 'uid';
  $handler->display->display_options['arguments']['uid']['default_action'] = 'default';
  $handler->display->display_options['arguments']['uid']['default_argument_type'] = 'current_user';
  $handler->display->display_options['arguments']['uid']['summary']['number_of_records'] = '0';
  $handler->display->display_options['arguments']['uid']['summary']['format'] = 'default_summary';
  $handler->display->display_options['arguments']['uid']['summary_options']['items_per_page'] = '25';
  $handler->display->display_options['block_description'] = 'Text Search Default';

  /* Display: Full */
  $handler = $view->new_display('block', 'Full', 'block_2');
  $handler->display->display_options['defaults']['filter_groups'] = FALSE;
  $handler->display->display_options['defaults']['filters'] = FALSE;
  /* Filter criterion: Content: Published */
  $handler->display->display_options['filters']['status']['id'] = 'status';
  $handler->display->display_options['filters']['status']['table'] = 'node';
  $handler->display->display_options['filters']['status']['field'] = 'status';
  $handler->display->display_options['filters']['status']['value'] = 1;
  $handler->display->display_options['filters']['status']['group'] = 1;
  $handler->display->display_options['filters']['status']['expose']['operator'] = FALSE;
  /* Filter criterion: Content: Type */
  $handler->display->display_options['filters']['type']['id'] = 'type';
  $handler->display->display_options['filters']['type']['table'] = 'node';
  $handler->display->display_options['filters']['type']['field'] = 'type';
  $handler->display->display_options['filters']['type']['value'] = array(
    'book' => 'book',
  );
  $handler->display->display_options['filters']['type']['group'] = 1;
  /* Filter criterion: Content: Content (field_book_content) */
  $handler->display->display_options['filters']['field_book_content_value']['id'] = 'field_book_content_value';
  $handler->display->display_options['filters']['field_book_content_value']['table'] = 'field_data_field_book_content';
  $handler->display->display_options['filters']['field_book_content_value']['field'] = 'field_book_content_value';
  $handler->display->display_options['filters']['field_book_content_value']['operator'] = 'contains';
  $handler->display->display_options['filters']['field_book_content_value']['exposed'] = TRUE;
  $handler->display->display_options['filters']['field_book_content_value']['expose']['operator_id'] = 'field_book_content_value_op';
  $handler->display->display_options['filters']['field_book_content_value']['expose']['description'] = 'Search the content of texts';
  $handler->display->display_options['filters']['field_book_content_value']['expose']['operator'] = 'field_book_content_value_op';
  $handler->display->display_options['filters']['field_book_content_value']['expose']['identifier'] = 'field_book_content_value';
  $handler->display->display_options['filters']['field_book_content_value']['expose']['remember'] = TRUE;
  $handler->display->display_options['filters']['field_book_content_value']['expose']['remember_roles'] = array(
    2 => '2',
    1 => '1',
    3 => '3',
  );

  /* Display: Title */
  $handler = $view->new_display('block', 'Title', 'block_3');
  $handler->display->display_options['defaults']['filter_groups'] = FALSE;
  $handler->display->display_options['defaults']['filters'] = FALSE;
  /* Filter criterion: Content: Published */
  $handler->display->display_options['filters']['status']['id'] = 'status';
  $handler->display->display_options['filters']['status']['table'] = 'node';
  $handler->display->display_options['filters']['status']['field'] = 'status';
  $handler->display->display_options['filters']['status']['value'] = 1;
  $handler->display->display_options['filters']['status']['group'] = 1;
  $handler->display->display_options['filters']['status']['expose']['operator'] = FALSE;
  /* Filter criterion: Content: Type */
  $handler->display->display_options['filters']['type']['id'] = 'type';
  $handler->display->display_options['filters']['type']['table'] = 'node';
  $handler->display->display_options['filters']['type']['field'] = 'type';
  $handler->display->display_options['filters']['type']['value'] = array(
    'book' => 'book',
  );
  $handler->display->display_options['filters']['type']['group'] = 1;
  /* Filter criterion: Content: Title */
  $handler->display->display_options['filters']['title']['id'] = 'title';
  $handler->display->display_options['filters']['title']['table'] = 'node';
  $handler->display->display_options['filters']['title']['field'] = 'title';
  $handler->display->display_options['filters']['title']['operator'] = 'contains';
  $handler->display->display_options['filters']['title']['group'] = 1;
  $handler->display->display_options['filters']['title']['exposed'] = TRUE;
  $handler->display->display_options['filters']['title']['expose']['operator_id'] = 'title_op';
  $handler->display->display_options['filters']['title']['expose']['description'] = 'Search the titles and subtitles of texts';
  $handler->display->display_options['filters']['title']['expose']['operator'] = 'title_op';
  $handler->display->display_options['filters']['title']['expose']['identifier'] = 'title';
  $handler->display->display_options['filters']['title']['expose']['remember_roles'] = array(
    2 => '2',
    1 => '1',
    3 => '3',
  );
  $handler->display->display_options['filters']['title']['expose']['autocomplete_items'] = '10';
  $handler->display->display_options['filters']['title']['expose']['autocomplete_min_chars'] = '0';
  $handler->display->display_options['filters']['title']['expose']['autocomplete_field'] = 'title';
  $handler->display->display_options['filters']['title']['expose']['autocomplete_raw_suggestion'] = 1;
  $handler->display->display_options['filters']['title']['expose']['autocomplete_raw_dropdown'] = 1;
  $handler->display->display_options['filters']['title']['expose']['autocomplete_dependent'] = 0;

  /* Display: My */
  $handler = $view->new_display('block', 'My', 'block_4');
  $handler->display->display_options['defaults']['filter_groups'] = FALSE;
  $handler->display->display_options['defaults']['filters'] = FALSE;
  /* Filter criterion: Content: Published */
  $handler->display->display_options['filters']['status']['id'] = 'status';
  $handler->display->display_options['filters']['status']['table'] = 'node';
  $handler->display->display_options['filters']['status']['field'] = 'status';
  $handler->display->display_options['filters']['status']['value'] = 1;
  $handler->display->display_options['filters']['status']['group'] = 1;
  $handler->display->display_options['filters']['status']['expose']['operator'] = FALSE;
  /* Filter criterion: Content: Type */
  $handler->display->display_options['filters']['type']['id'] = 'type';
  $handler->display->display_options['filters']['type']['table'] = 'node';
  $handler->display->display_options['filters']['type']['field'] = 'type';
  $handler->display->display_options['filters']['type']['value'] = array(
    'book' => 'book',
  );
  $handler->display->display_options['filters']['type']['group'] = 1;
  $export['text_search'] = $view;

  return $export;
}
