<?php

define('SHANTI_KMAPS_ADMIN_SERVICE', shanti_kmaps_admin_get_service_name());
define('SHANTI_KMAPS_ADMIN_SERVER_SUBJECTS','http://subjects.kmaps.virginia.edu');
define('SHANTI_KMAPS_ADMIN_SERVER_PLACES','http://places.kmaps.virginia.edu');
define('SHANTI_KMAPS_ADMIN_SERVER_SUBJECTS_EXPLORER','http://badger.drupal-dev.shanti.virginia.edu/subjects/__KMAPID__/overview/nojs');
define('SHANTI_KMAPS_ADMIN_SERVER_PLACES_EXPLORER','http://badger.drupal-dev.shanti.virginia.edu/places/__KMAPID__/overview/nojs');
define('SHANTI_KMAPS_ADMIN_SERVER_SOLR','http://kidx.shanti.virginia.edu/solr/kmindex-dev');
define('SHANTI_KMAPS_ADMIN_SERVER_SOLR_TERMS','http://kidx.shanti.virginia.edu/solr/termindex');
define('SHANTI_KMAPS_ADMIN_PATH', drupal_get_path('module','shanti_kmaps_admin'));
define('SHANTI_KMAPS_ADMIN_ASSET_TYPES','texts,photos,audio-video,visuals,sources,subjects,places,terms,maps,agents,events');

function shanti_kmaps_admin_menu() {
  return array(
    'admin/config/content/shanti_kmaps_admin' => array(
      'title' => 'SHANTI KMaps Admin',
      'description'       => 'Specify servers for pulling and pushing KMaps information.',
      'page callback'     => 'drupal_get_form',
      'page arguments'    => array('shanti_kmaps_admin_admin'),
      'access arguments'  => array('administer shanti_kmaps_admin'),
      'type'              => MENU_NORMAL_ITEM,      
    ),
    'shanti_kmaps_admin/test' => array(
      'title'             => 'SHANTI KMaps Admin Test',
      'page callback'     => 'shanti_kmaps_admin_test',
      'page arguments'    => '',
      'access arguments'  => array('administer shanti_kmaps_admin'),
      'type'              => MENU_NORMAL_ITEM,            
    ),
    'shanti_kmaps_admin/vars_json' => array(
      'title' => 'SHANTI KMaps Admin Vars as JSON',
      'page callback'     => 'shanti_kmaps_admin_vars_json',
      'page arguments'    => '',
      'access arguments'  => array('administer shanti_kmaps_admin'),
      'type'              => MENU_NORMAL_ITEM,            
    ),
  );
}

function shanti_kmaps_admin_permission() {
  return array(
    'administer shanti_kmaps_admin' => array(
      'title' => t('Administer SHANTI KMaps Admin'),
    ),
  );
}

function shanti_kmaps_admin_admin() {
  $form['shanti_kmaps_admin_server_subjects'] = array(
    '#type'           => 'textfield',
    '#title'          => t('KMaps Subjects Server'),
    '#default_value'  => variable_get('shanti_kmaps_admin_server_subjects', SHANTI_KMAPS_ADMIN_SERVER_SUBJECTS),
    '#size'           => 60,
    '#maxlength'      => 255,
    '#description'    => t('The server used to retrieve data for KMap subject terms. <br/>Do not include an end slash.'),
    '#required'       => TRUE,
  );
  $form['shanti_kmaps_admin_server_places'] = array(
    '#type'           => 'textfield',
    '#title'          => t('KMaps Places Server'),
    '#default_value'  => variable_get('shanti_kmaps_admin_server_places', SHANTI_KMAPS_ADMIN_SERVER_PLACES),
    '#size'           => 60,
    '#maxlength'      => 255,
    '#description'    => t('The server used to retrieve data for KMap place terms. <br/>Do not include an end slash.'),
    '#required'       => TRUE,
  );
  $form['shanti_kmaps_admin_root_subjects_id'] = array(
    '#type'           => 'textfield',
    '#title'          => t('Root KMaps Subjects ID'),
    '#default_value'  => variable_get('shanti_kmaps_admin_root_subjects_id', 6403),
    '#size'           => 20,
    '#maxlength'      => 30,
    '#description'    => t("The root subjects ID for this site. Defaults to 'Tibet and Himalyas'. You need to enter the numeric value."),
    '#required'       => FALSE,
  );
  $form['shanti_kmaps_admin_root_places_id'] = array(
    '#type'           => 'textfield',
    '#title'          => t('Root KMaps Places ID'),
    '#default_value'  => variable_get('shanti_kmaps_admin_root_places_id', 13735),
    '#size'           => 20,
    '#maxlength'      => 30,
    '#description'    => t("The root places ID for this site. Defaults to 'Earth'. You need to enter the numeric value."),
    '#required'       => FALSE,
  );
  $form['shanti_kmaps_admin_server_subjects_explorer'] = array(
    '#type'           => 'textfield',
    '#title'          => t('KMaps Subjects Explorer'),
    '#default_value'  => variable_get('shanti_kmaps_admin_server_subjects_explorer', SHANTI_KMAPS_ADMIN_SERVER_SUBJECTS_EXPLORER),
    '#size'           => 60,
    '#maxlength'      => 255,
    '#description'    => t('The site used to view and explore KMap subject terms in the SHANTI KMap Solr Index. <br/>Be sure to use the special string <b>__KMAP__</b> in the URL (with two underscores before and after the uppercase word "KMAP") to specify where the numeric KMap ID actually goes in the URL. <br/>Do not include an end slash.'),
    '#required'       => TRUE,
  );
  $form['shanti_kmaps_admin_server_places_explorer'] = array(
    '#type'           => 'textfield',
    '#title'          => t('KMaps Places Explorer'),
    '#default_value'  => variable_get('shanti_kmaps_admin_server_places_explorer', SHANTI_KMAPS_ADMIN_SERVER_PLACES_EXPLORER),
    '#size'           => 60,
    '#maxlength'      => 255,
    '#description'    => t('The site used to view and explore KMap place terms in the SHANTI KMap Solr Index. <br/>Be sure to use the special string <b>__KMAP__</b> in the URL (with two underscores before and after the uppercase word "KMAP") to specify where the numeric KMap ID actually goes in the URL. <br/>Do not include an end slash.'),
    '#required'       => TRUE,
  );
  $form['shanti_kmaps_admin_server_solr_opt_in'] = array(
    '#type'           => 'checkbox',
    '#title'          => t("Do you want to publish your KMap data to the SHANTI KMap Solr Index?"),
    '#description'    => t("If yes, then make sure you set the next field to a valid Solr URL."),
    '#default_value'  => variable_get('shanti_kmaps_admin_server_solr_opt_in', 0),
    '#options'        => array(0 => 'no', 1 => 'yes'),
  );
  $form['shanti_kmaps_admin_server_solr'] = array(
    '#type'           => 'textfield',
    '#title'          => t('KMaps Solr Server Assets Index'),
    '#default_value'  => variable_get('shanti_kmaps_admin_server_solr', SHANTI_KMAPS_ADMIN_SERVER_SOLR),
    '#size'           => 60,
    '#maxlength'      => 255,
    '#description'    => t("The URL to the SHANTI KMap Assets index. <br/>This may include a path to the specific index. <br/>Do not include an end slash."),
    '#required'       => FALSE,
  );
  $form['shanti_kmaps_admin_solr_filter_query'] = array(
    '#type'           => 'textfield',
    '#title'          => t('KMaps Solr Filter Query'),
    '#default_value'  => variable_get('shanti_kmaps_admin_solr_filter_query', ''),
    '#size'           => 60,
    '#maxlength'      => 255,
    '#description'    => t('Solr filter query to apply to all queries, e.g. <tt>fq=project:my_project OR fq=kmapid:places-99999</tt>.'),
    '#required'       => FALSE,
  );
  $form['shanti_kmaps_admin_server_solr_terms'] = array(
    '#type'           => 'textfield',
    '#title'          => t('KMaps Solr Server Terms Index'),
    '#default_value'  => variable_get('shanti_kmaps_admin_server_solr_terms', SHANTI_KMAPS_ADMIN_SERVER_SOLR_TERMS),
    '#size'           => 60,
    '#maxlength'      => 255,
    '#description'    => t("The URL to the SHANTI KMap Terms index. <br/>This may include a path to the specific index. <br/>Do not include an end slash."),
    '#required'       => FALSE,
  );
  $form['shanti_kmaps_admin_asset_types'] = array(
    '#type'           => 'textarea',
    '#title'          => t('KMaps Solr Asset Types'),
    '#default_value'  => variable_get('shanti_kmaps_admin_asset_types', SHANTI_KMAPS_ADMIN_ASSET_TYPES),
    '#description'    => t("A comma delimited list of asset types, used throughout the KMap system.<br/>These values should be lowercase plurals with no spaces.<br/>Ideally, this list would come from somewhere authoritative, such as the Rail KMaps server itself."),
    '#required'       => TRUE,
  );
  return system_settings_form($form);  
}

function shanti_kmaps_admin_admin_validate($form, &$form_state) {

  # Make sure a Solr index is specfified if they opt in
  if ($form_state['values']['shanti_kmaps_admin_server_solr_opt_in'] 
    && !$form_state['values']['shanti_kmaps_admin_server_solr']) {
    form_set_error('shanti_kmaps_admin_server_solr', 
      t('You must enter something for the Solr index, since you have chosen to publish to the SHANTI KMap Solr Index.')
    );
  }

  # Remove any spaces from the asset type string
  $asset_types = $form_state['values']['shanti_kmaps_admin_asset_types'];
  if (preg_match("/\s+/",$asset_types)) {
    $asset_types = preg_replace("/\s+/",'',$asset_types);
    form_set_value($form['shanti_kmaps_admin_asset_types'], $asset_types, $form_state);
    drupal_set_message("Removed extra spaces from the asset types list.");
  }

}

function shanti_kmaps_admin_test() {
  $vars = shanti_kmaps_admin_get_vars();
  dpm($vars);
}

function shanti_kmaps_admin_vars_json() {
  $vars = shanti_kmaps_admin_get_vars();
  drupal_json_output($vars);
}

function shanti_kmaps_admin_get_service_name() {
  return preg_replace("/[\.\/]/", '_', str_replace('http://', '', $GLOBALS['base_url']));
}

function shanti_kmaps_admin_preprocess_page() {
  $vars = shanti_kmaps_admin_get_vars();
  $vars['shanti_kmaps_admin_asset_types'] = shanti_kmaps_admin_get_asset_types();
  drupal_add_js(array('shanti_kmaps_admin' => $vars), 'setting');
}

function shanti_kmaps_admin_get_asset_types() {
  $types = array();
  $types = explode(',',variable_get('shanti_kmaps_admin_asset_types', SHANTI_KMAPS_ADMIN_ASSET_TYPES));
  return $types;
}

function shanti_kmaps_admin_get_vars() {
  $vars = array();
  $sql = "select `name`, `value` from {variable} where `name` like 'shanti_kmaps_admin%'";
  $rs = db_query($sql);
  foreach($rs as $r) {
    $vars[$r->name] = variable_get($r->name);
  }
  return $vars;
}
